Repository ThatConference/that.us, pull requests merged in 2020-09, with the labels that each got.

#317 prettier reinstalled and autofixed files.
  .prettierrc
  package-lock.json
  package.json
  src/components/home/CTA.svelte
  src/components/home/Hero.svelte
  src/components/home/NewMembers.svelte
  src/components/home/Newsletter.svelte
  src/components/home/Stats.svelte
  src/components/home/Testimonials.svelte
  src/components/my/ProfileForm.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/sessions/List.svelte
  src/components/sessions/SessionDetails.svelte
  src/components/sessions/SessionForm.svelte
  src/elements/Action.svelte
  src/elements/FeaturedSession.svelte
  src/utilities/scrollHelper.js
  src/utilities/truncate.js
Labels: bug

#318 Cs/pacakge bump
  package-lock.json
  package.json
  src/components/home/Events.svelte
  src/components/members/MemberCard.svelte
  src/components/my/ClaimTicketForm.svelte
  src/components/my/ProfileForm.svelte
  src/components/partners/PartnerCard.svelte
  src/components/sessions/Card.svelte
  src/components/sessions/KeynoteSpeaker.svelte
  src/elements/Image.svelte
  src/elements/modals/NoAction.svelte
  src/routes/Login.svelte
  src/routes/Members.svelte
  src/routes/Partners.svelte
  src/routes/help/Help.svelte
  src/routes/my/Profile.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/List.svelte
  tailwind.config.js
Labels: chore

#321 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: chore

#324 Update README.md
  README.md
Labels: chore

#323 Introducing the Activity Center and the new Changelog.
  .vscode/settings.json
  package-lock.json
  package.json
  public/_releaseNotes/1.0.0.aml
  public/_releaseNotes/1.1.0.aml
  public/_releaseNotes/1.2.0.aml
  public/_releaseNotes/manifest.aml
  public/images/activity-2.svg
  rollup.config.js
  src/App.svelte
  src/components/Footer.svelte
  src/components/activityCenter/ActivitySlideOver.svelte
  src/components/home/NewMembers.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/notifications/Warning.svelte
  src/components/releaseNotes/Release.svelte
  src/components/sessions/List.svelte
  src/elements/StandardLink.svelte
  src/elements/actions/clickOutside.js
  src/elements/actions/index.js
  src/elements/index.js
  src/elements/layouts/Simple.svelte
  src/elements/layouts/StackedLayout.svelte
  src/elements/overlays/BasicSlideOver.svelte
  src/elements/svgs/Activity.svelte
  src/elements/svgs/Left.svelte
  src/elements/svgs/Right.svelte
  src/elements/svgs/index.js
  src/elements/transisitions/expand.js
  src/routes/Test.svx.old
  src/routes/releases/ChangeLog.svelte
  src/routes/releases/Missed.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/List.svelte
  src/store/notificationCenter.js
  src/store/siteVersion.js
  todo.md
Labels: enhancement

#327 refactors link to the card, and not the text
  src/components/activityCenter/ActivitySlideOver.svelte
Labels: bug

#337 sponsors component is now event aware
  src/components/SponsorSimple.svelte
  src/routes/Test.svx.old
  src/routes/events/List.svelte
  src/routes/sessions/List.svelte
Labels: enhancement

#338 updates the zindex to appear over the home.
  src/components/nav/mainNav/MainNav.svelte
Labels: bug

#339 just hides the note on smaller displays
  src/components/sessions/List.svelte
Labels: enhancement

#346 calls login directly
  src/components/home/CTA.svelte
  src/components/home/Hero.svelte
  src/components/home/NewMembers.svelte
  src/components/home/Testimonials.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/mainNav/Desktop.svelte
  src/components/nav/mainNav/Mobile.svelte
Labels: enhancement

#347 join and favorite are always active
  src/components/sessions/Card.svelte
  src/components/sessions/SessionDetails.svelte
Labels: enhancement

#348 Adding better integration with Tidio Chat
  src/App.svelte
  src/routes/my/Badges.svelte
  src/routes/my/Profile.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/utilities/security.js
Labels: enhancement

#350 adds tidio api check before calling track
  src/App.svelte
  src/routes/my/Badges.svelte
  src/routes/my/Profile.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/utilities/eventTrack.js
  src/utilities/security.js
Labels: bug

#351 enables more room options for admins
  src/routes/join/Live.svelte
Labels: enhancement

#342 Added headroom menu
  package-lock.json
  package.json
  src/components/home/Hero.svelte
  src/components/home/NewMembers.svelte
  src/components/members/Hero.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/partners/Hero.svelte
  src/routes/Home.svelte
  src/routes/Members.svelte
Labels: enhancement

#357 updates layout for members and partners
  src/components/home/Hero.svelte
  src/components/members/Hero.svelte
  src/components/partners/Hero.svelte
  src/routes/Members.svelte
  src/routes/Partners.svelte
Labels: bug, enhancement

#358 redirects old sessions route
  src/App.svelte
  src/routes/SessionRedirect.svelte
Labels: enhancement

#359 Changes 'everyday' to 'every day' when used as adverb
  src/components/home/Hero.svelte
  src/components/home/Stats.svelte
  src/routes/Partners.svelte
Labels: bug

#362 package bumps
  package-lock.json
  package.json
Labels: chore

#363 fixes #361
  src/App.svelte
  src/components/Footer.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/routes/FAQ.svelte
  src/routes/support/FAQ.svelte
Labels: enhancement

#365 Adds help pages for new users
  package-lock.json
  public/_releaseNotes/1.3.0.aml
  public/images/ActivityCreateExample.jpg
  public/images/ActivityDetailExample.jpg
  public/images/ActivityJoinExample.jpg
  public/images/characters/Preston@2x.png
  src/App.svelte
  src/components/Footer.svelte
  src/elements/Tailwindcss.svelte
  src/elements/links/Highlight.svelte
  src/elements/links/Standard.svelte
  src/routes/NotFound.svelte
  src/routes/support/CreateAnActivity.svelte
  src/routes/support/FAQ.svelte
  src/routes/support/JoinAnActivity.svelte
  src/routes/support/JoiningAnActivity.svelte
  src/routes/support/StayingUpToDate.svelte
  src/routes/support/Welcome.svelte
  src/routes/support/WhatIsAnActivity.svelte
  src/routes/support/_Header.svelte
  src/routes/support/_Layout.svelte
Labels: documentation, enhancement

#366 FAQ's updated with new content
  package-lock.json
  package.json
  src/components/faq/FaqItem.svelte
  src/components/faq/items.json
  src/routes/support/FAQ.svelte
  src/routes/support/faqItems.json
Labels: WIP, documentation, enhancement

#367 remove incomplete faq entry
  src/routes/support/faqItems.json
Labels: bug

#369 adds search to activity screens
  src/components/activities/List.svelte
  src/routes/activities/List.svelte
Labels: enhancement

#370 sprint end version bump (1.3.0) and release notes
  package.json
  public/_releaseNotes/1.3.0.aml
  public/_releaseNotes/manifest.aml
Labels: chore

#372 add first and last name to Activities filter.
  package-lock.json
  src/components/activities/List.svelte
Labels: enhancement

#373 adds the new help to the nav menu
  public/_releaseNotes/1.4.0.aml
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/mainNav/links.js
Labels: enhancement

#374 increases padding on content layout to adjust for new nav
  src/routes/support/_Layout.svelte
Labels: bug

#375 updated colors
  src/components/releaseNotes/Release.svelte
  src/routes/releases/Missed.svelte
Labels: bug

#377 border color will update when an app is shared
  src/elements/layouts/StackedLayout.svelte
  src/routes/join/Live.svelte
Labels: enhancement

#379 updated the stats numbers
  src/components/home/Stats.svelte
Labels: chore

#381 Package Bumps and Bug Fixes
  package-lock.json
  package.json
  src/components/SponsorSimple.svelte
Labels: bug, chore

#383 updates content
  src/routes/support/CreateAnActivity.svelte
  src/routes/support/JoiningAnActivity.svelte
  src/routes/support/StayingUpToDate.svelte
  src/routes/support/Welcome.svelte
  src/routes/support/WhatIsAnActivity.svelte
Labels: chore, documentation
