Repository ThatConference/that.us, pull requests merged in 2020-07, with the labels that each got.

#15 updates the routing on authentication
  src/utilities/security.js
Labels: bug

#18 blocks on logout
  src/utilities/security.js
Labels: bug

#20 adds the abiltiy to join via querystring
  package.json
  src/components/sessions/Card.svelte
  src/routes/sessions/SessionDetails.svelte
  src/utilities/security.js
Labels: enhancement

#25 redirects after login back to org page
  src/App.svelte
  src/routes/Login.svelte
  src/routes/sessions/Session.svelte
  src/utilities/security.js
Labels: enhancement

#26 Updates the session's lists to include a item key.
  src/components/sessions/List.svelte
Labels: bug

#27 updates copy on cancel button
  src/routes/sessions/Create.svelte
Labels: bug

#28 Session Detail Enhancements
  src/components/sessions/Card.svelte
  src/elements/Tag.svelte
  src/elements/index.js
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
  todo.md
Labels: enhancement

#44 resolves issue #43
  src/routes/sessions/SessionDetails.svelte
  todo.md
Labels: enhancement

#45 hides disqus on auth
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#46 enables social icons for session details
  src/components/social/SocialLink.svelte
  src/components/social/index.js
  src/elements/layouts/StackedLayout.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: enhancement

#48 truncates long descriptions on session list
  src/components/sessions/Card.svelte
Labels: enhancement

#49 login / logout hangs
  src/config.js
  src/utilities/security.js
Labels: WIP

#50 Join link uses Link.
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#51 just a quick update
  README.md
Labels: documentation

#52 adds the favicon
  public/favicon.png
  public/index.html
Labels: bug

#54 updates footer, nav, mobile nav on home and childern
  src/components/Footer.svelte
  src/components/home/Hero.svelte
  src/components/home/index.js
  src/components/home/nav/Desktop.svelte
  src/components/home/nav/MainNav.svelte
  src/components/home/nav/Mobile.svelte
  src/components/home/nav/links.js
  src/components/index.js
  src/components/nav/Large.svelte
  src/components/nav/Mobile.svelte
  src/components/nav/Top.svelte
  src/elements/Footer.svelte
  src/elements/index.js
  src/elements/layouts/StackedLayout.svelte
  src/routes/Home.svelte
Labels: enhancement

#60 spelling is hard
  src/components/nav/Mobile.svelte
Labels: bug

#63 adds favorites to the details screen
  src/components/Footer.svelte
  src/components/nav/Large.svelte
  src/components/nav/Mobile.svelte
  src/elements/Avatars.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: enhancement

#65 graph client creations happens in page
  src/components/sessions/Card.svelte
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/submissions.js
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/List.svelte
Labels: bug

#66 sets the page title
  src/routes/join/Live.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: enhancement

#68 sets the favorite on the sessions page
  src/components/sessions/Card.svelte
  src/components/sessions/List.svelte
  src/dataSources/api.that.tech/favorites.js
  src/routes/sessions/List.svelte
Labels: enhancement

#70 updates copy on the tags label
  src/routes/sessions/Create.svelte
Labels: bug

#69 set the page title to static data
  src/routes/join/Live.svelte
Labels: bug

#71 adds faq page
  package-lock.json
  package.json
  rollup.config.js
  src/App.svelte
  src/components/faq/FaqItem.svelte
  src/components/faq/items.json
  src/routes/FAQ.svelte
Labels: enhancement

#72 fixed up sponsor spacing
  src/components/SponsorSimple.svelte
  src/elements/layouts/StackedLayout.svelte
Labels: bug

#74 adds member listing page
  package-lock.json
  package.json
  public/images/ClarkJaimee.jpg
  src/App.svelte
  src/components/Footer.svelte
  src/components/home/Hero.svelte
  src/components/home/index.js
  src/components/members/Hero.svelte
  src/components/members/MemberCard.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/interiorNav/Top.svelte
  src/components/nav/mainNav/Desktop.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/nav/mainNav/Mobile.svelte
  src/components/nav/mainNav/links.js
  src/dataSources/api.that.tech/members.js
  src/elements/layouts/StackedLayout.svelte
  src/routes/FAQ.svelte
  src/routes/Members.svelte
  src/routes/join/Live.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/Session.svelte
Labels: enhancement

#76 centering all the things
  src/routes/sessions/Create.svelte
Labels: bug

#78 reworked how favorties are structured and save state
  src/components/sessions/Card.svelte
  src/components/sessions/List.svelte
  src/dataSources/api.that.tech/favorites.js
  src/routes/my/Favorites.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: bug, enhancement

#80 added partners
  src/App.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/partners/Hero.svelte
  src/components/partners/PartnerCard.svelte
  src/config.js
  src/dataSources/api.that.tech/partners.js
  src/routes/Partners.svelte
Labels: enhancement

#82 adds loading indicators to partners, members, etc
  src/components/CardLoader.svelte
  src/components/sessions/List.svelte
  src/elements/GroupHeader.svelte
  src/elements/index.js
  src/routes/Members.svelte
  src/routes/Partners.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/List.svelte
Labels: enhancement

#83 updates home page copy
  package-lock.json
  package.json
  src/components/home/Testimonials.svelte
  src/routes/Home.svelte
Labels: enhancement

#84 just bumping package versions
  package-lock.json
  package.json
Labels: chore

#85 because andrew said so
  src/components/home/Hero.svelte
Labels: enhancement

#86 rips off top padding.
  src/components/partners/Hero.svelte
Labels: bug

#87 fixes name on alt for nav
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: bug

#88 ripping out alt tag values
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: bug

#91 fixed up copy
  src/components/home/Testimonials.svelte
Labels: bug

#81 Initial FAQ Content
  public/global.css
  src/components/faq/FaqItem.svelte
  src/components/faq/items.json
  src/routes/FAQ.svelte
Labels: enhancement

#104 We wern't spelling weren't properly
  src/routes/sessions/Session.svelte
Labels: bug

#105 starting the day crushing the bugs
  src/components/members/MemberCard.svelte
  src/components/partners/PartnerCard.svelte
  src/components/sessions/Card.svelte
  src/components/social/SocialLink.svelte
  src/dataSources/api.that.tech/members.js
  src/dataSources/api.that.tech/sessions.js
  src/routes/sessions/Create.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#131 readme love
  .all-contributorsrc
  README.md
Labels: enhancement

#123 Adds Profile Form
  .eslintrc
  package-lock.json
  package.json
  src/App.svelte
  src/components/Footer.svelte
  src/components/members/New.svelte
  src/components/my/NewMemberForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/sessions/Card.svelte
  src/components/sessions/List.svelte
  src/components/sessions/SessionForm.svelte
  src/dataSources/api.that.tech/members.js
  src/routes/my/New.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
  todo.md
Labels: WIP

#136 adds profile awesome
  package-lock.json
  package.json
  src/App.svelte
  src/components/faq/items.json
  src/components/my/ProfileForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/config.js
  src/dataSources/api.that.tech/members.js
  src/routes/my/New.svelte
  src/routes/my/Profile.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/List.svelte
  src/utilities/security.js
  todo.md
Labels: enhancement

#137 adds user account info to the nav
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: enhancement

#138 brings nav to top on click
  src/components/nav/interiorNav/Large.svelte
Labels: bug

#142 Typo / Copy Fixes
  src/components/my/ProfileForm.svelte
Labels: bug

#139 default images, warning dialogs
  src/components/members/MemberCard.svelte
  src/elements/index.js
  src/elements/modals/Warning.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
Labels: bug, enhancement

#143 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#144 fixes up copy on favorites
  src/routes/sessions/SessionDetails.svelte
Labels: enhancement

#145 adds tidio chat
  src/App.svelte
Labels: enhancement

#147 adds auth checks
  src/App.svelte
  src/components/my/ProfileForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/notifications/CreateProfile.svelte
  src/components/notifications/NoProfile.svelte
  src/components/sessions/Card.svelte
  src/components/sessions/SessionForm.svelte
  src/elements/LinkButton.svelte
  src/elements/layouts/StackedLayout.svelte
  src/elements/modals/Error.svelte
  src/routes/join/Live.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/SessionDetails.svelte
  src/store/profileNotification.js
  todo.md
Labels: bug, enhancement

#149 updates members copy
  src/components/members/Hero.svelte
Labels: enhancement

#155 fixes missing images on nav
  src/components/my/ProfileForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: bug

#156 adds the speakers name to the card
  src/components/sessions/Card.svelte
Labels: enhancement

#160 adds a success indicator to a new session
  src/components/notifications/CreateProfile.svelte
  src/components/notifications/NoProfile.svelte
  src/components/notifications/Success.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: enhancement

#161 fixes null reference
  src/dataSources/api.that.tech/submissions.js
Labels: bug

#164 fixes tag state
  src/components/SponsorSimple.svelte
  src/components/sessions/SessionForm.svelte
Labels: bug, enhancement

#167 fixes default images and smashed input
  src/components/members/MemberCard.svelte
  src/components/my/ProfileForm.svelte
  src/components/sessions/Card.svelte
  src/config.js
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#169 adds copy to thank partners
  src/components/partners/Hero.svelte
Labels: bug

#171 updates url and opens in a new tab
  src/components/partners/Hero.svelte
Labels: bug

#172 truncates long email
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: bug

#173 adds error message on invalid form
  src/App.svelte
  src/components/my/ProfileForm.svelte
  src/components/notifications/Error.svelte
Labels: bug, enhancement

#174 pulling out keynote times
  src/components/sessions/sessionTimes.js
Labels: chore

#175 fixing background default
  src/components/members/MemberCard.svelte
  src/components/sessions/Card.svelte
Labels: bug, enhancement

#177 readme cleanup
  .all-contributorsrc
  README.md
  package-lock.json
  package.json
Labels: chore

#179 opens tickets in a new window
  src/components/home/Hero.svelte
Labels: bug

#180 Fix links in FAQ
  src/components/faq/items.json
Labels: bug

#181 Add "Log Out" link to Home/FAQ page header
  src/components/nav/mainNav/Desktop.svelte
Labels: bug

#185 add tech check reference, fix Safari bullets
  public/global.css
  src/components/faq/items.json
Labels: bug, enhancement

#187 adds warning around muted
  src/components/notifications/Warning.svelte
  src/elements/ActionHeader.svelte
  src/routes/join/Live.svelte
Labels: enhancement

#191 add defaultProfileImage to Avatar
  src/config.js
  src/elements/Avatars.svelte
Labels: bug

#192 adds back the new properites
  src/routes/my/Profile.svelte
Labels: bug

#193 adds click to unmute
  src/components/notifications/Warning.svelte
  src/routes/join/Live.svelte
Labels: enhancement

#194 adds some analytics
  src/App.svelte
  src/config.js
  src/routes/my/Profile.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/utilities/gtag.js
Labels: enhancement

#195 upon hangup we redirect back to sessions
  src/routes/join/Live.svelte
  todo.md
Labels: enhancement

#200 sets focus on the jitsi control
  src/routes/join/Live.svelte
Labels: enhancement

#203 validate slug prior to checking uniqueness.
  src/components/my/ProfileForm.svelte
Labels: enhancement

#204 Fix typo
  src/components/my/ProfileForm.svelte
Labels: bug

#206 package updates
  package-lock.json
  package.json
Labels: chore

#205 size jitsi frame to window; add expand/shrink
  src/elements/layouts/StackedLayout.svelte
  src/routes/join/Live.svelte
Labels: bug, enhancement

#208 enables the join button based on startTime
  src/components/FirstTimeVisitor.svelte
  src/components/sessions/Card.svelte
  src/routes/sessions/SessionDetails.svelte
  todo.md
Labels: enhancement

#210 enables profile links on the profile update screen
  package-lock.json
  package.json
  src/components/my/ProfileForm.svelte
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/members.js
  src/routes/my/Profile.svelte
  src/utilities/security.js
Labels: enhancement

#211 updates copy for social links
  src/components/my/ProfileForm.svelte
Labels: bug

#212 removes test code for start time
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#215 logs user's session attendance
  src/dataSources/api.that.tech/sessions.js
  src/routes/join/Live.svelte
Labels: enhancement

#216 made the timezone message red
  src/routes/sessions/List.svelte
Labels: enhancement

#218 wip: badge claims
  jitsi-rules.md
  src/App.svelte
  src/components/members/MemberCard.svelte
  src/components/my/ClaimTicketForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/sessions/Card.svelte
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/me.js
  src/dataSources/api.that.tech/members.js
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/submissions.js
  src/routes/my/Badges.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
  src/utilities/security.js
  todo.md
Labels: enhancement

#221 fixes new user social link check
  src/components/my/ProfileForm.svelte
Labels: bug

#223 missing profileSlug for url
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/submissions.js
Labels: bug

#226 Reworked the hero copy on the home page.
  src/components/home/Hero.svelte
Labels: enhancement

#230 adds the shell of the help page
  src/App.svelte
  src/components/Footer.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/routes/help/Help.svelte
Labels: enhancement

#231 keynote cards
  src/components/CardLoader.svelte
  src/components/sessions/KeynoteCard.svelte
  src/components/sessions/KeynoteSpeaker.svelte
  src/components/sessions/List.svelte
  src/dataSources/api.that.tech/sessions.js
  src/routes/sessions/Session.svelte
Labels: enhancement

#232 fixes padding on lg
  src/components/sessions/KeynoteSpeaker.svelte
Labels: bug

#233 adds panel card
  src/components/sessions/KeynoteCard.svelte
  src/components/sessions/List.svelte
Labels: enhancement

#234 swapped to an svg to fix hero image
  public/images/thatOnline.svg
  src/components/home/Hero.svelte
Labels: bug
