Repository ThatConference/that.us, pull requests merged in 2020-10, with the labels that each got.

#388 increase padding inside the Nav component parent
  src/elements/layouts/_NavWrapper.svelte
Labels: bug

#387 Add signup button to Mobile and Desktop NavBar
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
Labels: enhancement, hacktoberfest

#382 Adds the Community and Member Profile Pages
  package-lock.json
  package.json
  public/images/logos/logo-javascript.svg
  public/images/logos/logo-nodejs.svg
  public/images/that-animated.svg
  src/App.svelte
  src/components/Modal.svelte
  src/components/activities/ActivityDetails.svelte
  src/components/activities/Card.svelte
  src/components/activities/List.svelte
  src/components/activities/UpNextHero.svelte
  src/components/activities/UpNextMemberHero.svelte
  src/components/home/UpNext.svelte
  src/components/members/MemberCard.svelte
  src/components/my/ProfileForm.svelte
  src/dataSources/api.that.tech/members.js
  src/elements/Avatars.svelte
  src/elements/CTA.svelte
  src/elements/FeaturedActivity-Add.svelte
  src/elements/FeaturedActivityDetail.svelte
  src/elements/buttons/Highlight.svelte
  src/elements/buttons/Standard.svelte
  src/elements/index.js
  src/elements/layouts/Profile.svelte
  src/elements/layouts/_BaseContent.svelte
  src/elements/layouts/_NavWrapper.svelte
  src/elements/layouts/profile/_Header.svelte
  src/elements/svgs/TreesAnimated.svelte
  src/elements/svgs/index.js
  src/routes/Home.svelte
  src/routes/communities/Community.svelte
  src/routes/communities/_CTA.svelte
  src/routes/communities/_Hero.svelte
  src/routes/communities/_NewestFollowers.svelte
  src/routes/communities/_UpNext.svelte
  src/routes/members/Member.svelte
  src/routes/members/Members.svelte
  src/routes/members/_CTA.svelte
  src/routes/members/_Hero.svelte
  src/routes/members/_LifeHack.svelte
  src/routes/members/_MemberCore.svelte
  src/routes/members/_MeritBadges.svelte
  src/routes/members/_NewestFollowers.svelte
  src/routes/members/_UpNext.svelte
  src/routes/my/Badges.svelte
  src/routes/support/StayingUpToDate.svelte
  src/utilities/transistions/expand.js
  tailwind.config.js
  todo.md
Labels: WIP, enhancement

#393 fixes issue #392
  src/components/members/MemberCard.svelte
Labels: bug

#391 Fixing Tidio Problem
  src/App.svelte
  src/components/notifications/Error.svelte
Labels: bug, hacktoberfest

#397 move from onMount to tidio's onReady
  src/App.svelte
Labels: enhancement

#398 updates links to use relative paths
  src/components/activities/ActivityDetails.svelte
  src/components/activities/Card.svelte
  src/components/members/MemberCard.svelte
  src/elements/Avatars.svelte
Labels: bug

#399 adds interests and lifehack to profile
  src/components/activities/ActivityForm.svelte
  src/components/my/ProfileForm.svelte
  src/dataSources/api.that.tech/me.js
  src/dataSources/api.that.tech/members.js
  src/utilities/security.js
Labels: enhancement

#400 fixing up english words
  src/components/my/ProfileForm.svelte
Labels: bug

#402 package bumps
  package-lock.json
  package.json
  rollup.config.js
Labels: chore

#404 adds sessions to members, fixes quote and badges
  src/dataSources/api.that.tech/members.js
  src/elements/FeaturedActivityDetail.svelte
  src/routes/members/_LifeHack.svelte
  src/routes/members/_MemberCore.svelte
  src/routes/members/_UpNext.svelte
Labels: enhancement

#405 Member's sessions are now filtered.
  src/dataSources/api.that.tech/members.js
  src/routes/members/_UpNext.svelte
Labels: enhancement

#408 trimming default values
  src/components/my/ProfileForm.svelte
Labels: bug

#406 added sprints release notes
  public/_releaseNotes/1.4.0.aml
  public/_releaseNotes/manifest.aml
Labels: chore, documentation

#410 updating version to 1.4.0
  package.json
Labels: chore

#412 closes issue #411
  src/App.svelte
  src/routes/members/_MemberCore.svelte
Labels: enhancement

#415 Enables communities and community pages
  public/images/THAT-blue.svg
  public/images/logos/logo-javascript.svg
  public/images/logos/logo-nodejs.svg
  src/App.svelte
  src/components/activities/ActivityDetails.svelte
  src/components/communities/CommunityCard.svelte
  src/components/members/MemberCard.svelte
  src/dataSources/api.that.tech/communities.js
  src/elements/Waiting.svelte
  src/elements/modals/NoAction.svelte
  src/elements/svgs/TreesAnimated.svelte
  src/routes/communities/Communities.svelte
  src/routes/communities/Community.svelte
  src/routes/communities/_CommunitiesHero.svelte
  src/routes/communities/_CommunityCore.svelte
  src/routes/communities/_Hero.svelte
  src/routes/communities/_UpNext.svelte
  src/routes/members/Members.svelte
  src/routes/members/_UpNext.svelte
Labels: enhancement

#419 updates layout for the member cards on the hero
  public/images/logos/logo-javascript.svg
  public/images/logos/logo-nodejs.svg
  src/components/home/NewMembers.svelte
Labels: bug

#420 Nav Updates
  src/components/nav/_UserProfile.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/mainNav/Desktop.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/nav/mainNav/links.js
  src/elements/FeaturedActivity-Add.svelte
  src/elements/FeaturedActivity.svelte
  src/elements/FeaturedActivityDetail.svelte
Labels: enhancement

#424 adjusting for new schema
  src/dataSources/api.that.tech/sessions.js
Labels: bug, chore

#426 fixes partners not returning
  src/dataSources/api.that.tech/partners.js
Labels: bug

#431 fixes #430 and removes disqus
  public/index.html
  src/components/activities/ActivityDetails.svelte
  src/components/activities/ActivityForm.svelte
Labels: bug, chore

#421 Enables a member the ability to follow a community
  .vscode/settings.json
  package-lock.json
  package.json
  src/App.svelte
  src/components/activities/ActivityDetails.svelte
  src/components/activities/List.svelte
  src/components/activities/UpNext.svelte
  src/components/activities/UpNextHero.svelte
  src/components/communities/CommunityCard.svelte
  src/dataSources/api.that.tech/communities.js
  src/dataSources/api.that.tech/community/mutations.js
  src/dataSources/api.that.tech/community/queries.js
  src/dataSources/api.that.tech/me/queries.js
  src/dataSources/api.that.tech/submissions.js
  src/elements/FeaturedActivity-Add.svelte
  src/elements/FeaturedActivity.svelte
  src/elements/FeaturedActivityDetail.svelte
  src/elements/FeaturedActivityLoading.svelte
  src/elements/activities.js
  src/main.js
  src/routes/communities/Communities.svelte
  src/routes/communities/Community.svelte
  src/routes/communities/_CTA.svelte
  src/routes/communities/_CommunitiesHero.svelte
  src/routes/communities/_CommunityCore.svelte
  src/routes/communities/_Hero.svelte
  src/routes/communities/_NewestFollowers.svelte
  src/routes/communities/_UpNext.svelte
  src/routes/communities/machines/activities.js
  src/routes/communities/machines/communities.js
  src/routes/communities/machines/community.js
  src/routes/communities/machines/follow.js
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/utilities/security.js
  todo.md
Labels: enhancement

#434 fixes breaking change related to urql major upgrade
  src/routes/join/Live.svelte
Labels: bug

#435 adds header copy to the communities page
  src/routes/communities/_CommunitiesHero.svelte
  todo.md
Labels: enhancement

#436 updates release notes for sprint end, bumps to 1.5.0
  package.json
  public/_releaseNotes/1.5.0.aml
  public/_releaseNotes/manifest.aml
  todo.md
Labels: chore

#441 Updates Major and Minor Pacakges
  package-lock.json
  package.json
Labels: chore

#443 rolled back infinite scroll to working version
  package-lock.json
  package.json
Labels: bug

#445 bumps svelte-infinite-scroll to latest
  package-lock.json
  package.json
Labels: bug, chore

#444 converts member listing page backing to paged state machine
  src/components/home/NewMembers.svelte
  src/components/my/ClaimTicketForm.svelte
  src/components/my/ProfileForm.svelte
  src/dataSources/api.that.tech/members/mutations.js
  src/dataSources/api.that.tech/members/queries.js
  src/machines/paging.js
  src/routes/members/Member.svelte
  src/routes/members/Members.svelte
  src/routes/members/machines/members.js
  src/routes/my/Badges.svelte
  src/routes/my/Profile.svelte
Labels: enhancement

#447 converts partner listing backing to new paged state machine
  src/dataSources/api.that.tech/community/queries.js
  src/routes/communities/Communities.svelte
  src/routes/communities/machines/communities.js
Labels: enhancement

#448 updates nav button style to match both navs
  src/components/nav/mainNav/Desktop.svelte
Labels: enhancement

#449 fixes button state issue
  src/components/activities/UpNext.svelte
Labels: bug

#450 putting it on a keto diet
  src/components/activities/ActivityDetails.svelte
  src/components/activities/ActivityForm.svelte
  src/components/activities/Card.svelte
  src/components/nav/_UserProfile.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/elements/layouts/StackedLayout.svelte
  src/routes/Partners.svelte
  src/routes/activities/List.svelte
  src/routes/join/Live.svelte
  src/routes/members/Members.svelte
  src/routes/releases/ChangeLog.svelte
  src/routes/releases/Missed.svelte
Labels: chore

#452 converts partner listing backing to new paged state machine
  src/App.svelte
  src/components/partners/PartnerCard.svelte
  src/dataSources/api.that.tech/partner/queries.js
  src/routes/Partners.svelte
  src/routes/partners/Partner.svelte
  src/routes/partners/Partners.svelte
  src/routes/partners/machines/partners.js
Labels: chore, enhancement

#459 Sets better default values for oauth providers
  src/routes/my/Profile.svelte
Labels: bug

#460 added in default profile image for member spotlight
  src/routes/members/_Hero.svelte
Labels: bug

#455 Add activity list tag filter
  src/components/activities/FilterSlideOver.svelte
  src/components/activities/List.svelte
  src/elements/overlays/BasicSlideOver.svelte
Labels: WIP, enhancement

#462 refreshing our home page stats
  src/components/home/Stats.svelte
Labels: chore
