Repository ThatConference/that.us, pull requests merged in 2020-08, with the labels that each got.

#241 changed the interval to 1sec
  src/components/sessions/Card.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#249 calling resize on load
  src/routes/join/Live.svelte
Labels: bug

#255 undo filtering
  src/components/sessions/List.svelte
  src/routes/sessions/List.svelte
Labels: chore

#266 fixes #263
  src/components/sessions/Card.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#270 redirect new user to signup rather than login
  src/components/home/Hero.svelte
  src/routes/Login.svelte
  src/utilities/security.js
Labels: enhancement

#271 Fix typo in query
  src/routes/sessions/Session.svelte
Labels: bug

#262 Post 8/3
  package-lock.json
  package.json
  src/App.svelte
  src/components/CardLoader.svelte
  src/components/Footer.svelte
  src/components/my/ProfileForm.svelte
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/mainNav/links.js
  src/components/sessions/Card.svelte
  src/components/sessions/List.svelte
  src/components/sessions/PanelSpeakers.svelte
  src/components/sessions/SessionForm.svelte
  src/components/social/SocialLink.svelte
  src/config.js
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/submissions.js
  src/elements/ActionHeader.svelte
  src/elements/GroupHeader.svelte
  src/routes/join/Live.svelte
  src/routes/my/Badges.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/Session.svelte
  src/routes/sessions/SessionDetails.svelte
  src/routes/sessions/formatRequest.js
  src/store/currentEvent.js
  src/utilities/auth-OLD.js
Labels: enhancement

#275 adds dead join button, url state fixes
  src/components/sessions/List.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/List.svelte
  src/routes/sessions/SessionDetails.svelte
  todo.md
Labels: enhancement

#277 helps if you have the href
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#276 updates button copy
  src/routes/my/Submissions.svelte
Labels: chore

#278 fixes the id
  src/routes/sessions/SessionDetails.svelte
Labels: bug

#284 closes #282
  src/dataSources/api.that.tech/sessions.js
  src/routes/sessions/List.svelte
Labels: bug

#285 removes auth token on anon/public calls
  src/dataSources/api.that.tech/members.js
  src/dataSources/api.that.tech/partners.js
  src/dataSources/api.that.tech/sessions.js
Labels: enhancement

#288 subtracts a day to return todays sessions
  src/dataSources/api.that.tech/sessions.js
Labels: bug

#289 adds ical integration
  package-lock.json
  package.json
  public/global.css
  rollup.config.js
  src/components/CardLoader.svelte
  src/components/faq/FaqItem.svelte
  src/elements/GroupHeader.svelte
  src/routes/sessions/SessionDetails.svelte
  src/utilities/ical.js
Labels: enhancement

#290 removes subtracting the day
  src/dataSources/api.that.tech/sessions.js
Labels: bug

#292 board gets all sessions starting TODAY
  src/dataSources/api.that.tech/sessions.js
Labels: bug

#293 fixes cards tags position
  src/components/sessions/Card.svelte
  src/elements/Tag.svelte
Labels: bug

#305 wip - seo
  public/googlef6298c37a15dd561.html
  public/images/og-logo.png
  public/index.html
  public/robots.txt
  public/sitemap.xml
  src/App.svelte
  src/components/members/New.svelte
  src/components/sessions/SessionDetails.svelte
  src/components/sessions/sessionTimes.js
  src/routes/FAQ.svelte
  src/routes/Home.svelte
  src/routes/Login.svelte
  src/routes/Logout.svelte
  src/routes/Members.svelte
  src/routes/Partners.svelte
  src/routes/events/List.svelte
  src/routes/join/Live.svelte
  src/routes/my/Badges.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Profile.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/Create.svelte
  src/routes/sessions/Edit.svelte
  src/routes/sessions/List.svelte
  src/store/metaTags.js
  src/utilities/seo/OpenGraph.svelte
  src/utilities/seo/metaTags.js
  todo.md
Labels: enhancement

#307 adds that-api-* header for that-site
  src/App.svelte
  src/dataSources/api.that.tech/members.js
  src/dataSources/api.that.tech/partners.js
  src/dataSources/api.that.tech/sessions.js
Labels: chore

#308 reworked cards action buttons
  src/components/sessions/Card.svelte
  src/components/sessions/CardLink.svelte
  src/components/sessions/SessionDetails.svelte
Labels: enhancement

#309 join button always shows
  src/components/sessions/Card.svelte
  src/components/sessions/SessionDetails.svelte
  src/components/sessions/elements/CalendarButton.svelte
  src/config.js
Labels: enhancement

#312 it helps when you subtract from two different values
  src/components/sessions/Card.svelte
Labels: bug

#310 Home Page Launch
  package-lock.json
  package.json
  public/images/THAT-Logo-Words.svg
  public/images/THAT-blue.svg
  public/images/THAT-red.svg
  public/images/whiteSquare.svg
  src/App.svelte
  src/components/Footer.svelte
  src/components/home/CTA.svelte
  src/components/home/Event.svelte
  src/components/home/Events.svelte
  src/components/home/Features.svelte
  src/components/home/Hero.svelte
  src/components/home/NewMembers.svelte
  src/components/home/Newsletter.svelte
  src/components/home/Sponsors.svelte
  src/components/home/Stats.svelte
  src/components/home/Testimonials.svelte
  src/components/home/UpNext.svelte
  src/components/home/index.js
  src/components/nav/interiorNav/Large.svelte
  src/components/nav/mainNav/Desktop.svelte
  src/components/nav/mainNav/MainNav.svelte
  src/components/sessions/Card.svelte
  src/components/sessions/List.svelte
  src/components/sessions/SessionDetails.svelte
  src/components/sessions/elements/CalendarButton.svelte
  src/components/social/SocialLink.svelte
  src/dataSources/api.that.tech/members.js
  src/dataSources/api.that.tech/sessions.js
  src/elements/FeaturedSession.svelte
  src/elements/Logo.svelte
  src/elements/index.js
  src/routes/Home.svelte
  src/routes/events/List.svelte
  src/routes/my/Favorites.svelte
  src/routes/my/Submissions.svelte
  src/routes/sessions/List.svelte
  src/utilities/ical.js
  todo.md
Labels: enhancement

#316 fixes data in post to AC
  src/components/home/Newsletter.svelte
Labels: bug
