Repository ThatConference/that.us, pull requests merged in 2021-11, with the labels that each got.

#1076 correct date on workshop ticket bullets
  src/routes/events/_components/tickets/_Workshops.svelte
Labels: bug

#1080 Part #1 of New Profile Bug
  src/_components/nav/_UserProfile.svelte
  src/_components/notifications/CreateProfile.svelte
  src/_components/notifications/Error.svelte
  src/_components/notifications/NoProfile.svelte
  src/_components/notifications/Success.svelte
  src/global.css
  src/routes/blog/rss.xml.js
  src/routes/events/_components/Notices.svelte
  src/routes/my/profiles/primary.svelte
  src/routes/my/submissions/index.svelte
Labels: bug, critical

#1081 Profile Issue Part Deuce
  src/_dataSources/api.that.tech/me.js
  src/hooks/index.js
  src/routes/__error.svelte
Labels: bug, critical

#1083 adds blog post
  src/_blog/posts/2021-11-08-freshwater-sauces/index.md
Labels: documentation

#1077 Updates focus for links and keyboard accessibility
  src/_components/activities/UpNext.svelte
  src/_components/footer/Footer.svelte
  src/_components/nav/_UserProfile.svelte
  src/_components/nav/interiorNav/Large.svelte
  src/_components/nav/mainNav/Desktop.svelte
  src/_components/social/SocialLink.svelte
  src/routes/_root/components/hero.svelte
  src/routes/_root/components/upNext.svelte
Labels: enhancement, ui/ux

#1075 fix YouTube base url changing logic
  .vscode/launch.json
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug

#1087 null reference exception
  src/_components/activities/Card.svelte
Labels: bug, critical

#1089 adds check to make sure a user has sessions
  src/routes/speakers/_components/formSections/NoSessions.svelte
  src/routes/speakers/accept/_machine/config.js
  src/routes/speakers/accept/_machine/index.js
  src/routes/speakers/accept/index.svelte
Labels: enhancement

#1090 adding import
  src/_elements/FeaturedActivity.svelte
Labels: bug, critical

#1091 adds blog post
  src/_blog/getPosts.js
  src/_blog/posts/2021-11-17-speaker-announcement/index.md
  src/_components/SponsorSimple.svelte
  src/_components/blog/latest.svelte
  src/routes/blog/posts/__layout.svelte
  src/routes/index.svelte
Labels: blog posts

#1092 Adds aria-labels to svg social icon links
  src/_components/footer/Footer.svelte
  src/_components/footer/socials.js
  src/_components/members/MemberCard.svelte
  src/_components/social/SocialLink.svelte
  src/routes/join/[activityId]/index.svelte
Labels: ui/ux, accessibility

#1098 Cs/1097
  .node-version
  package-lock.json
  src/_utils/error.js
Labels: bug, chore

#1099 no more object object
  src/routes/__error.svelte
Labels: bug
