Repository ThatConference/that.us, pull requests merged in 2021-09, with the labels that each got.

#861 cs/url
  src/_components/nav/mainNav/links.js
Labels: bug, kit

#864 fixes #863
  src/routes/my/components/profiles/ProfileForm.svelte
Labels: bug, critical

#865 package bump
  package-lock.json
  package.json
Labels: chore

#866 fixes #863 in kit migration
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug, critical

#877 removing old data access function
  src/_dataSources/api.that.tech/events/queries.js
  src/_dataSources/api.that.tech/products/queries.js
Labels: bug, kit

#878 global search and replace gone wrong, fixing link
  src/app.html
Labels: bug, kit

#881 validate there is a `socialLink` value prior to using it
  src/routes/my/components/profiles/ProfileForm.svelte
Labels: bug

#880 verify socialLink var has value before using it
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug

#887 updates activities/create && backdoor
  scratch.txt
  src/routes/activities/_components/form/ActivityForm.svelte
  src/routes/activities/_components/form/_Event.svelte
  src/routes/activities/create/__layout.svelte
  src/routes/activities/create/backdoor.svelte
  src/routes/activities/create/index.svelte
  src/routes/activities/post-create.svelte
Labels: bug, kit

#886 add env support for Vite.
  .eslintrc.cjs
  package-lock.json
  package.json
  src/_utils/config.js
Labels: bug, kit

#892 Refactors Edit Activity, Fixes Select Box, Adds CFP Route
  src/_components/activities/ActivityForm.svelte
  src/_dataSources/api.that.tech/sessions/queries.js
  src/routes/activities/_components/form/_Attributes.svelte
  src/routes/activities/_components/form/_Audience.svelte
  src/routes/activities/_components/form/_Event.svelte
  src/routes/activities/_components/form/_When.svelte
  src/routes/activities/create/backdoor.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/activities/edit/[activityId].svelte
  src/routes/activities/edit/__layout.svelte
Labels: bug, kit

#893 fixes #883
  src/_components/activities/Card.svelte
  src/_dataSources/api.that.tech/favorites.js
Labels: bug, kit

#894 fixes #884
  src/_dataSources/api.that.tech/members/mutations.js
  src/routes/members/[member]/index.svelte
Labels: bug, kit

#897 adds in our 3rd party integrations
  src/app.html
  src/routes/__layout.svelte
Labels: bug, critical, kit

#898 fixes #896
  src/_dataSources/api.that.tech/favorites.js
Labels: bug, kit

#899 fixes #885
  src/routes/my/profiles/_components/sharedProfileForm.svelte
Labels: bug, kit

#900 adds custom error page
  src/routes/__error.svelte
  src/routes/not-found.svelte
Labels: bug, kit

#901 updates to use load, fixes seo
  src/routes/events/[event]/[date]/index.svelte
Labels: bug, kit

#902 adds account verification check
  src/routes/__layout.svelte
Labels: bug, kit

#903 reworks the cancel/withdraw on activity edit
  src/routes/activities/_components/form/ActivityForm.svelte
  src/routes/activities/edit/[activityId].svelte
Labels: bug, kit

#904 adds secure loading to partner and event pages
  src/routes/event/__layout.svelte
  src/routes/event/check-in/[eventName]/[year]/index.svelte
  src/routes/event/check-in/_components/_CheckinModal.svelte
  src/routes/event/check-in/_components/_EditCheckInModal.svelte
  src/routes/event/check-in/_components/_Loading.svelte
  src/routes/event/check-in/_components/_Order.svelte
  src/routes/event/check-in/_components/_OrderView.svelte
  src/routes/event/check-in/_components/_RegistrationList.svelte
  src/routes/event/check-in/_components/_SemiCircle.svelte
  src/routes/event/check-in/_components/_Ticket.svelte
  src/routes/event/check-in/_components/_TicketView.svelte
  src/routes/partners/leads/__layout.svelte
  src/routes/partners/leads/index.svelte
  src/routes/partners/my-network/__layout.svelte
  src/routes/partners/my-network/index.svelte
Labels: bug, kit

#910 adding some more info around logging
  src/app.html
  src/hooks/index.js
  src/routes/__layout.svelte
  src/routes/api/auth/proxy.js
Labels: bug

#911 adds aggressive logging around callback
  src/routes/api/auth/callback.js
Labels: bug

#913 adds more logging, removes service worker
  src/routes/api/auth/callback.js
  src/routes/login.js
  src/service-worker.js
Labels: bug

#914 adds logging in auth wrapper
  src/_utils/security/wrappers.js
Labels: bug

#917 polyfiling fetch
  package-lock.json
  package.json
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
Labels: bug

#918 actually importing correctly
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
Labels: bug

#919 converts to isomorphic-fetch
  package-lock.json
  package.json
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
Labels: bug

#920 adding post
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
  src/routes/login.js
Labels: bug

#921 removes woopra call
  src/routes/__layout.svelte
Labels: bug

#922 reworking how jitsi loads
  package-lock.json
  package.json
  src/_dataSources/api.that.tech/sessions.js
  src/_utils/config.js
  src/_utils/gfetch.js
  src/app.html
  src/routes/join/[activityId]/index.svelte
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug

#923 updates the activity id param for edit.
  src/routes/activities/edit/[activityId].svelte
Labels: bug

#924 fixes router references
  src/routes/membership/_components/pricing/_Hero.svelte
Labels: bug

#925 session is updated on profile change
  src/routes/my/profiles/primary.svelte
Labels: bug

#926 references.....
  src/routes/my/profiles/primary.svelte
Labels: bug

#927 rolling back debug session changes
  src/_dataSources/api.that.tech/sessions.js
Labels: chore

#928 credentials include
  src/_utils/gfetch.js
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
Labels: bug

#929 fixed upload profile image
  src/hooks/index.js
  src/routes/join/[activityId]/index.svelte
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug

#930 Catch and Query Cleanup
  src/_dataSources/api.that.tech/events/queries.js
  src/_utils/gfetch.js
  src/routes/activities/create/__layout.svelte
  src/routes/activities/edit/__layout.svelte
  src/routes/index.svelte
Labels: bug, enhancement

#931 fixing buttons making awesome
  package-lock.json
  package.json
  src/_elements/buttons/Shell.svelte
  src/_elements/links/StandardScroll.svelte
  src/routes/events/_components/hybrid/_Hero.svelte
Labels: bug

#932 adding service worker
  src/service-worker.js
Labels: bug

#933 adds account validation to secure pages
  src/_utils/security/auth.js
  src/hooks/index.js
Labels: bug

#934 adding logging around auth handler for debugging
  src/_utils/security/wrappers.js
  src/routes/api/auth/callback.js
Labels: bug, debugging

#935 adding logging around auth handler for debugging
  src/routes/api/auth/callback.js
Labels: debugging

#936 adding logging around auth handler for debugging
  src/_utils/config.js
  src/_utils/security/wrappers.js
  src/routes/api/auth/callback.js
Labels: debugging

#937 downgrading auth0
  package-lock.json
  package.json
Labels: debugging

#938 context -> stuff
  src/_utils/security/auth.js
  src/routes/__layout.svelte
  src/routes/activities/[state]/[year]/__layout.svelte
  src/routes/activities/[state]/[year]/index.svelte
  src/routes/activities/create/__layout.svelte
  src/routes/activities/create/backdoor.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/activities/create/index.svelte
  src/routes/activities/edit/[activityId].svelte
  src/routes/activities/edit/__layout.svelte
Labels: chore

#939 links and upgrade
  package-lock.json
  package.json
  src/_components/nav/_UserProfile.svelte
Labels: debugging

#940 maybe a button??
  src/_components/nav/_UserProfile.svelte
Labels: debugging

#941 removing a catch
  src/_components/nav/_UserProfile.svelte
  src/_utils/security/wrappers.js
Labels: debugging

#942 debugging
  src/_utils/security/wrappers.js
Labels: debugging

#943 no after callback
  src/routes/api/auth/callback.js
Labels: debugging

#944 right back to where we started
  src/_utils/security/wrappers.js
  src/routes/api/auth/callback.js
Labels: debugging

#945 adding more server setings
  src/_utils/config.js
Labels: debugging

#946 config changes
  src/_utils/config.js
Labels: debugging

#947 rolling back
  src/_utils/config.js
Labels: debugging

#948 hard coding conifg
  src/_utils/config.js
Labels: debugging

#949 relative paths again
  src/_utils/config.js
Labels: debugging

#950 relative paths updates no trailing slashes
  src/_utils/config.js
Labels: debugging

#951 cookie http/https
  src/_utils/config.js
Labels: debugging

#952 no redirect on login
  src/_utils/config.js
  src/routes/login.js
Labels: debugging

#953 no try/catch on callback
  src/routes/api/auth/callback.js
  src/routes/login.js
Labels: debugging

#954 lets add a let
  src/routes/join/[activityId]/index.svelte
Labels: bug, critical

#955 updates window title and url
  src/routes/join/[activityId]/index.svelte
Labels: enhancement

#956 redirect me babyy
  src/routes/api/auth/callback.js
Labels: debugging

#957 redirect me babyy
  src/routes/api/auth/callback.js
Labels: bug, debugging

#958 redirect me babyyyy
  src/routes/api/auth/callback.js
Labels: debugging

#959 where there is a will there is a way
  src/_utils/security/wrappers.js
  src/routes/api/auth/callback.js
Labels: bug, debugging

#960 where there is a will there is a way maybe
  src/_utils/security/wrappers.js
Labels: debugging

#961 more poking and hoping
  src/_utils/security/auth.js
  src/_utils/security/wrappers.js
Labels: debugging

#962 trailing slash
  svelte.config.js
Labels: debugging

#963 rolling back
  src/_utils/security/wrappers.js
  svelte.config.js
Labels: bug, debugging

#964 playing with strings
  src/_utils/config.js
  src/_utils/security/auth.js
Labels: bug, debugging

#965 debug debug debug
  src/_utils/config.js
  src/routes/api/auth/callback.js
  src/routes/login.js
Labels: debugging

#966 debug debug debug
  src/_utils/config.js
Labels: debugging

#967 fixes authenticated call on member listing
  src/routes/members/[member]/index.svelte
Labels: bug

#968 post launch fixes
  package-lock.json
  src/routes/api/auth/proxy.js
Labels: WIP

#969 fixes broken reference on my-network
  src/routes/partners/my-network/__layout.svelte
  src/routes/partners/my-network/index.svelte
Labels: bug

#970 __error now logs to sentry
  src/routes/__error.svelte
Labels: enhancement, debugging

#971 moving db call into layout
  src/_dataSources/api.that.tech/partner/leads/queries.js
  src/routes/partners/my-network/__layout.svelte
  src/routes/partners/my-network/index.svelte
Labels: bug

#972 updating some api config stuff
  src/_utils/gfetch.js
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
Labels: bug

#973 more logging
  src/_dataSources/api.that.tech/partner/leads/queries.js
  src/routes/__error.svelte
Labels: debugging

#974 more logging
  src/routes/api/auth/proxy.js
Labels: debugging

#975 more logging
  src/_utils/gfetch.js
  svelte.config.js
Labels: bug, debugging

#976 changing to a relative path
  src/_utils/gfetch.js
Labels: debugging

#977 cleaning up from debugging session
  src/_dataSources/api.that.tech/partner/leads/queries.js
  src/_utils/gfetch.js
  src/routes/api/auth/proxy.js
  svelte.config.js
Labels: bug

#978 updating url to be dynamic based on location
  src/_utils/gfetch.js
Labels: bug

#979 logging updates
  package.json
  src/hooks/index.js
  svelte.config.js
Labels: chore

#980 adds fetch retry
  package-lock.json
  package.json
  src/_utils/gfetch.js
Labels: enhancement

#981 fixes fetch retry??
  src/_utils/gfetch.js
Labels: bug

#984 fixes #983
  src/routes/activities/edit/[activityId].svelte
Labels: bug, critical

#986 adds back user metrics
  src/app.html
  src/routes/__layout.svelte
Labels: enhancement

#987 adding browser checks
  src/routes/__layout.svelte
  src/routes/event/check-in/_components/_CheckinModal.svelte
  src/routes/event/check-in/_components/_EditCheckInModal.svelte
  src/routes/partners/leads/[eventId].svelte
Labels: bug, critical
