Repository ThatConference/that.us, pull requests merged in 2021-02, with the labels that each got.

#561 Issue 531, fixing weird sticky date behavior
  src/components/activities/List.svelte
  tailwind.config.js
Labels: bug, enhancement

#570 Issue 514 communities filter
  src/components/activities/FilterSlideOver.svelte
  src/components/activities/List.svelte
  src/dataSources/api.that.tech/sessions.js
  src/elements/overlays/BasicSlideOver.svelte
Labels: enhancement

#571 Issue 562
  public/images/characters/sasquatch.png
  src/components/activities/List.svelte
Labels: enhancement

#572 local storage cart is now versioned
  src/utilities/cart/cartMachine.js
Labels: enhancement

#575 Introduces New Settings, Refactors Stacked Layout
  package-lock.json
  package.json
  src/Router.svelte
  src/components/nav/_UserProfile.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/interiorNav/Top.svelte
  src/elements/layouts/StackedLayout.svelte
  src/elements/svgs/Badge.svelte
  src/elements/svgs/CreditCard.svelte
  src/elements/svgs/Ticket.svelte
  src/elements/svgs/User.svelte
  src/elements/svgs/index.js
  src/routes/LoginSuccess.svelte
  src/routes/my/Badges.svelte
  src/routes/my/Settings.svelte
  src/routes/my/components/_Badges.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_Profile.svelte
  src/routes/my/components/_Tickets.svelte
  src/utilities/security.js
  tailwind.config.js
Labels: enhancement

#576 Package Dependencies Updates
  package-lock.json
  package.json
Labels: chore

#579 Addresses issue 573
  src/dataSources/api.that.tech/favorites.js
  src/dataSources/api.that.tech/submissions.js
Labels: bug

#577 order summary screen
  src/components/my/ClaimTicketForm.svelte
  src/components/my/ProfileForm.svelte
  src/dataSources/api.that.tech/orders/queries.js
  src/elements/svgs/ChevronRight.svelte
  src/elements/svgs/index.js
  src/machines/paging.js
  src/routes/membership/components/pricing/_FAQ.svelte
  src/routes/my/Settings.svelte
  src/routes/my/components/_Badges.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/machines/orderHistory.js
  src/routes/orders/Success.svelte
  src/routes/orders/components/_Cart.svelte
  src/utilities/cart/cartMachine.js
Labels: enhancement

#574 Issue 565
  src/App.svelte
  src/components/activities/List.svelte
  src/elements/overlays/BasicSlideOver.svelte
Labels: enhancement

#581 removing z-index on callout cards
  src/routes/membership/components/pricing/_EventTickets.svelte
  src/routes/membership/components/pricing/_Hero.svelte
Labels: bug

#583 Overall Cleanup and Base Layout
  src/Router.svelte
  src/components/activities/ActivityForm.svelte
  src/components/nav/_UserProfile.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/notifications/CreateProfile.svelte
  src/components/notifications/NoProfile.svelte
  src/elements/modals/NoAction.svelte
  src/routes/join/Live.svelte
  src/routes/membership/components/pricing/_EventTickets.svelte
  src/routes/membership/components/pricing/_Hero.svelte
  src/routes/membership/components/pricing/_NotReady.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_Profile.svelte
  src/routes/orders/Cancelled.svelte
  src/routes/orders/Success.svelte
  src/routes/orders/components/_CartItem.svelte
  src/routes/orders/components/_Steps.svelte
  src/routes/support/CreateAnActivity.svelte
  src/routes/support/Welcome.svelte
Labels: enhancement

#584 Order Receipts Linked
  src/dataSources/api.that.tech/orders/queries.js
  src/routes/my/components/_OrderHistory.svelte
Labels: enhancement

#585 fixes metaTags on new pages
  src/routes/LoginSuccess.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/orders/Cancelled.svelte
  src/routes/orders/Success.svelte
  src/routes/orders/Summary.svelte
Labels: bug

#586 more metatag fixes
  src/routes/LoginSuccess.svelte
  src/routes/NotFound.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_Profile.svelte
  src/routes/orders/Cancelled.svelte
  src/routes/orders/Success.svelte
  src/routes/orders/Summary.svelte
Labels: bug

#587 adds event ticket allocations screen
  src/dataSources/api.that.tech/orders/queries.js
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_Tickets.svelte
  src/routes/my/machines/allocations.js
Labels: enhancement

#588 sets default bulk purchase and quantities
  .prettierrc
  .vscode/settings.json
  src/routes/membership/components/pricing/_AnnualMembership.svelte
  src/routes/membership/components/pricing/_EventTickets.svelte
  src/routes/membership/components/pricing/_Hero.svelte
  src/utilities/cart/cartMachine.js
Labels: enhancement

#589 Fixes root page bugs
  .eslintrc
  .prettierrc
  .vscode/settings.json
  package-lock.json
  package.json
  src/components/activities/UpNext.svelte
  src/components/home/Features.svelte
  src/components/home/NewMembers.svelte
  src/components/home/index.js
  src/elements/Logo.svelte
Labels: bug

#590 Adds Multi-Event Support to the Root Page
  src/components/home/Event.svelte
  src/components/home/Events.svelte
  src/dataSources/api.that.tech/events/queries.js
  src/routes/home/Home.svelte
Labels: enhancement

#592 fixes layout issues and missssspelings
  src/components/home/Event.svelte
  src/components/home/Events.svelte
Labels: bug

#593 New Routing, Multi-Event Activity Pages, and Paging
  package-lock.json
  src/App.svelte
  src/Router.svelte
  src/components/activities/List.svelte
  src/config.js
  src/dataSources/api.that.tech/sessions.js
  src/machines/paging.js
  src/routes/activities/Activity.svelte
  src/routes/activities/Create.svelte
  src/routes/activities/Daily.svelte
  src/routes/activities/Edit.svelte
  src/routes/activities/Event.svelte
  src/routes/activities/List.svelte
  src/routes/activities/lib/formatRequest.js
  src/routes/activities/machines/daily.js
  src/routes/activities/machines/event.js
  src/routes/events/Event.svelte
  src/routes/events/Events.svelte
  src/routes/events/components/_Hybrid.svelte
  src/routes/events/components/_Online.svelte
  src/routes/my/Settings.svelte
Labels: WIP, enhancement

#595 introduces events landing page
  src/dataSources/api.that.tech/events/queries.js
  src/routes/events/Events.svelte
  src/routes/events/components/_EventCard.svelte
  src/routes/events/components/_EventsHero.svelte
Labels: enhancement

#596 removing editor goo
  src/routes/events/Events.svelte
Labels: bug

#598 refactors based on api/data event updates
  src/components/home/Events.svelte
  src/routes/events/Events.svelte
  src/routes/events/components/_EventCard.svelte
Labels: enhancement

#599 fixes mouse hover on feature add card
  src/elements/FeaturedActivity-Add.svelte
Labels: bug

#600 updates default config accounting for api/event data changes
  src/config.js
Labels: chore

#601 Event Landing Page
  package-lock.json
  package.json
  postcss.config.js
  src/components/Footer.svelte
  src/components/SponsorSimple.svelte
  src/components/activities/List.svelte
  src/components/activities/UpNextEvent.svelte
  src/components/home/CTA.svelte
  src/components/home/NewMembers.svelte
  src/components/nav/_UserProfile.svelte
  src/dataSources/api.that.tech/events/queries.js
  src/dataSources/api.that.tech/orders/queries.js
  src/elements/CTA.svelte
  src/elements/layouts/ContentLayout.svelte
  src/elements/layouts/LandingLayout.svelte
  src/elements/layouts/StackedLayout.svelte
  src/elements/layouts/_BaseContent.svelte
  src/elements/layouts/_NavWrapper.svelte
  src/elements/links/Highlight.svelte
  src/elements/svgs/ChevronRight.svelte
  src/elements/svgs/illustrations/Code.svelte
  src/elements/svgs/illustrations/index.js
  src/routes/activities/Event.svelte
  src/routes/events/Event.svelte
  src/routes/events/components/_EventCTA.svelte
  src/routes/events/components/_EventCard.svelte
  src/routes/events/components/_EventFollowers.svelte
  src/routes/events/components/_EventTicket.svelte
  src/routes/events/components/_Online.svelte
  src/routes/events/components/_OnlineHero.svelte
  src/routes/my/Settings.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_Tickets.svelte
  src/routes/orders/components/_Cart.svelte
  src/utilities/cart/cartMachine.js
  tailwind.config.js
Labels: enhancement

#603 adds event sponsor listing page
  src/Router.svelte
  src/components/partners/Hero.svelte
  src/components/partners/_SimpleHero.svelte
  src/routes/communities/_CommunitiesHero.svelte
  src/routes/partners/EventPartners.svelte
  src/routes/partners/machines/partners.js
Labels: enhancement

#604 Copy Review and Updates
  src/routes/events/components/_EventTicket.svelte
  src/routes/events/components/_Online.svelte
  src/routes/membership/Pricing.svelte
  src/routes/membership/components/pricing/_AnnualMembership.svelte
  src/routes/membership/components/pricing/_EventTickets.svelte
  src/routes/membership/components/pricing/_Quote.svelte
Labels: enhancement
