Repository ThatConference/that.us, pull requests merged in 2021-06, with the labels that each got.

#747 references are hard
  src/components/cta/_CallForSpeakers.svelte
Labels: bug, critical

#753 adds post create method
  src/Router.svelte
  src/routes/activities/Create.svelte
  src/routes/activities/PostCreate.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Event.svelte
Labels: enhancement

#756 updating favicon location for og:image
  public/index.html
Labels: bug

#759 updating to match schema
  src/dataSources/api.that.tech/orders/mutations.js
Labels: bug, critical

#760 Issue 754 edit activity wrong events are being listed
  src/routes/activities/Edit.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Event.svelte
  src/routes/activities/components/form/_SectionTitle.svelte
Labels: bug, enhancement

#764 adds placeholder text
  src/routes/my/components/_TicketAllocation.svelte
Labels: bug

#767 counselor acceptance form
  src/Router.svelte
  src/routes/speakers/Accept.svelte
  src/routes/speakers/components/_Layout.svelte
  src/routes/speakers/components/_QuestionModal.svelte
Labels: bug, enhancement

#768 changing QUERY_NEXT_SESSIONS to return event object.
  src/dataSources/api.that.tech/sessions.js
Labels: bug, critical

#769 respects the current status if it exists
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/schemas.js
  src/routes/activities/lib/formatRequest.js
Labels: bug, critical

#770 updated the link
  src/routes/speakers/Accept.svelte
Labels: bug

#772 Extend session details
  src/components/activities/ActivityDetails.svelte
  src/components/activities/Card.svelte
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/sessions/queries.js
  src/routes/activities/Activity.svelte
  src/routes/activities/machines/daily.js
  src/utilities/seo/metaTags.js
Labels: critical, enhancement

#776 Update fuse using svelte reactive.
  src/components/activities/List.svelte
Labels: bug

#780 Fixed regression, calendar button available for in-person sessions.
  src/components/activities/ActivityDetails.svelte
Labels: regression

#786 Added mapping for fullname to support search.
  src/components/activities/List.svelte
Labels: enhancement

#789 adds staybridge
  src/routes/support/Travel.svelte
Labels: enhancement

#787 Restyled the mobile menu for activities for all states.
  src/components/nav/interiorNav/Mobile.svelte
Labels: enhancement

#788 Added concept for Camp Counselor sessions. Also fixed "phantom" shadow on sticky scroll.
  public/images/Trees-Solid-White.svg
  src/components/activities/ActivityDetails.svelte
  src/components/activities/Card.svelte
  src/components/activities/List.svelte
  src/components/social/SocialLink.svelte
Labels: enhancement

#791 Added threshold check for mobile and desktop
  src/routes/activities/Daily.svelte
Labels: enhancement
