Repository ThatConference/that.us, pull requests merged in 2021-01, with the labels that each got.

#546 Package Updates and Breaking Changes Refactored.
  package-lock.json
  package.json
  rollup.config.js
  src/components/activities/ActivityForm.svelte
Labels: chore

#547 Adds shopping cart state machine and logic
  .env-cmdrc.json
  package-lock.json
  public/index.html
  rollup.config.js
  src/Router.svelte
  src/config.js
  src/dataSources/api.that.tech/orders/mutations.js
  src/dataSources/api.that.tech/orders/queries.js
  src/dataSources/api.that.tech/products/queries.js
  src/routes/orders/Cancel.svelte
  src/routes/orders/Success.svelte
  src/routes/orders/Verify.svelte
  src/utilities/cart/cartConfig.js
  src/utilities/cart/cartMachine.js
  src/utilities/cart/index.js
Labels: enhancement

#554 adds border to the input elements
  src/components/activities/ActivityForm.svelte
  src/components/activities/FilterSlideOver.svelte
  src/components/activities/List.svelte
  src/components/my/ClaimTicketForm.svelte
  src/components/my/ProfileForm.svelte
Labels: bug

#555 updates missing border
  src/components/my/ProfileForm.svelte
Labels: bug

#549 Adds Order Summary Page
  src/Router.svelte
  src/components/activities/ActivityForm.svelte
  src/components/activities/FilterSlideOver.svelte
  src/components/activities/List.svelte
  src/components/my/ClaimTicketForm.svelte
  src/components/my/ProfileForm.svelte
  src/elements/svgs/Step.svelte
  src/elements/svgs/StepComplete.svelte
  src/main.js
  src/routes/orders/Success.svelte
  src/routes/orders/Summary.svelte
  src/routes/orders/Test.svelte
  src/routes/orders/Verify.svelte
  src/routes/orders/components/_Cart.svelte
  src/routes/orders/components/_CartItem.svelte
  src/routes/orders/components/_Layout.svelte
  src/routes/orders/components/_Steps.svelte
  src/routes/orders/machines/steps.js
  src/routes/orders/machines/stepsConfig.js
  src/routes/orders/machines/summary.js
  src/routes/orders/machines/summaryConfig.js
  src/utilities/cart/cartConfig.js
  src/utilities/cart/cartMachine.js
Labels: enhancement

#557 Fixing issue #534
  src/routes/partners/Partners.svelte
Labels: bug

#559 Added endOfLine: 'auto' in prettier configs
  .prettierrc
Labels: bug

#560 Grid items' height now consistent in their row
  src/components/communities/CommunityCard.svelte
  src/routes/communities/Communities.svelte
Labels: bug
