Repository ThatConference/that.us, pull requests merged in 2021-05, with the labels that each got.

#708 Updates graph order type for me.
  src/dataSources/api.that.tech/orders/queries.js
Labels: bug, critical

#709 updates gql to match new schema
  src/dataSources/api.that.tech/sessions.js
Labels: enhancement

#706 hybrid event form updates
  public/index.html
  src/App.svelte
  src/Router.svelte
  src/components/home/Hero.svelte
  src/components/home/Newsletter.svelte
  src/components/home/Testimonials.svelte
  src/config.js
  src/dataSources/api.that.tech/events/queries.js
  src/dataSources/api.that.tech/sessions/mutations.js
  src/dataSources/api.that.tech/sessions/queries.js
  src/dataSources/api.that.tech/submissions.js
  src/dataSources/api.that.tech/utilities/error.js
  src/elements/modals/Error.svelte
  src/routes/activities/Create.svelte
  src/routes/activities/Edit.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Audience.svelte
  src/routes/activities/components/form/_Event.svelte
  src/routes/activities/components/form/_Prerequisites.svelte
  src/routes/activities/components/form/_Resources.svelte
  src/routes/activities/components/form/_SectionTitle.svelte
  src/routes/activities/components/form/_Support.svelte
  src/routes/activities/components/form/_What.svelte
  src/routes/activities/components/form/_When.svelte
  src/routes/activities/components/form/_WorkshopDetails.svelte
  src/routes/activities/components/form/components/_AdditionalResources.svelte
  src/routes/activities/components/form/components/_TakeAways.svelte
  src/routes/activities/components/form/initialValues.js
  src/routes/activities/components/form/schemas.js
  src/routes/activities/lib/formatRequest.js
  src/routes/my/Submissions.svelte
  src/routes/my/components/_Badges.svelte
  src/routes/my/components/_Profile.svelte
  src/routes/my/components/_Submission.svelte
  src/routes/my/components/_SubmissionList.svelte
  src/routes/orders/ThatSuccess.svelte
  src/routes/orders/components/_Cart.svelte
Labels: bug, enhancement

#712 updates takeaway to act more like the rest of the forms
  src/routes/activities/components/form/components/_AdditionalResources.svelte
  src/routes/activities/components/form/components/_TakeAways.svelte
Labels: bug

#713 adding stripe load back
  src/routes/orders/components/_Cart.svelte
Labels: bug, critical

#714 removes panel sessions from CFP
  src/routes/activities/components/form/_Attributes.svelte
Labels: enhancement

#715 fixes display value of enum based drop downs
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Audience.svelte
Labels: bug

#716 removes keynote from the keynote schema
  src/routes/activities/components/form/schemas.js
  src/routes/activities/lib/formatRequest.js
Labels: bug

#717 updates copy and steps
  src/routes/activities/components/_Steps.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Prerequisites.svelte
  src/routes/activities/components/form/_Resources.svelte
  src/routes/activities/components/form/_SectionTitle.svelte
  src/routes/activities/components/form/_Support.svelte
  src/routes/activities/components/form/_What.svelte
  src/routes/activities/components/form/_WorkshopDetails.svelte
Labels: enhancement

#719 fixing copy mistakes
  src/routes/activities/components/form/_What.svelte
Labels: bug

#718 updates the api endpoint
  src/config.js
Labels: chore

#724 fixes #720
  src/routes/activities/lib/formatRequest.js
Labels: bug, critical

#725 fixes #723
  src/routes/activities/components/form/initialValues.js
Labels: bug, critical

#726 fixes #721
  src/routes/activities/components/_Step.svelte
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Audience.svelte
Labels: bug, critical

#727 Reset Location and StartTime
  src/routes/activities/lib/formatRequest.js
Labels: bug

#728 Date wasn't being populated on edit
  src/dataSources/api.that.tech/sessions/queries.js
  src/routes/activities/components/form/initialValues.js
Labels: bug, critical

#729 removing invalid api input options
  src/routes/activities/lib/formatRequest.js
Labels: bug

#730 release notes
  public/_releaseNotes/1.10.0.aml
Labels: chore

#731 brett wanted the years to be correct
  public/_releaseNotes/1.10.0.aml
  public/_releaseNotes/1.9.0.aml
  public/_releaseNotes/1.9.1.aml
Labels: bug

#705 Call For Speakers
  package-lock.json
  package.json
  public/_releaseNotes/1.10.0.aml
  public/_releaseNotes/1.9.0.aml
  public/_releaseNotes/1.9.1.aml
  public/_releaseNotes/manifest.aml
  public/index.html
  src/App.svelte
  src/Router.svelte
  src/components/home/Hero.svelte
  src/components/home/Newsletter.svelte
  src/components/home/Testimonials.svelte
  src/config.js
  src/dataSources/api.that.tech/events/queries.js
  src/dataSources/api.that.tech/sessions/mutations.js
  src/dataSources/api.that.tech/sessions/queries.js
  src/dataSources/api.that.tech/submissions.js
  src/dataSources/api.that.tech/utilities/error.js
  src/elements/modals/Error.svelte
  src/routes/activities/Create.svelte
  src/routes/activities/Edit.svelte
  src/routes/activities/components/_Step.svelte
  src/routes/activities/components/_Steps.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Audience.svelte
  src/routes/activities/components/form/_Event.svelte
  src/routes/activities/components/form/_Prerequisites.svelte
  src/routes/activities/components/form/_Resources.svelte
  src/routes/activities/components/form/_SectionTitle.svelte
  src/routes/activities/components/form/_Support.svelte
  src/routes/activities/components/form/_What.svelte
  src/routes/activities/components/form/_When.svelte
  src/routes/activities/components/form/_WorkshopDetails.svelte
  src/routes/activities/components/form/components/_AdditionalResources.svelte
  src/routes/activities/components/form/components/_TakeAways.svelte
  src/routes/activities/components/form/initialValues.js
  src/routes/activities/components/form/schemas.js
  src/routes/activities/lib/formatRequest.js
  src/routes/my/Submissions.svelte
  src/routes/my/components/_Badges.svelte
  src/routes/my/components/_Profile.svelte
  src/routes/my/components/_Submission.svelte
  src/routes/my/components/_SubmissionList.svelte
  src/routes/orders/ThatSuccess.svelte
Labels: Release, bug, enhancement

#734 Fixed #733 Spelling: Payment Recieved #733
  src/routes/orders/Success.svelte
  src/routes/orders/ThatSuccess.svelte
  src/routes/orders/components/_QuestionModal.svelte
Labels: bug

#738 added landing page /activities/call-for-counselors
  public/images/characters/bear-eyelashes.png
  public/images/characters/bear-pig.png
  public/images/characters/conference_ticket.svg
  public/images/characters/hotel_accomodations.svg
  public/images/characters/professionally_recorded.svg
  src/Router.svelte
  src/dataSources/api.that.tech/events/queries.js
  src/routes/activities/CallForCounselors.svelte
  src/routes/activities/components/cfp/_CTA.svelte
  src/routes/activities/components/cfp/_EventMeta.svelte
  src/routes/activities/components/cfp/_FAQ.svelte
  src/routes/activities/components/cfp/_Perks.svelte
  src/routes/events/Event.svelte
Labels: enhancement

#735 CFP Landing Page
  package.json
  public/_releaseNotes/1.10.1.aml
  public/_releaseNotes/manifest.aml
  public/images/characters/bear-eyelashes.png
  public/images/characters/bear-pig.png
  public/images/characters/conference_ticket.svg
  public/images/characters/hotel_accomodations.svg
  public/images/characters/professionally_recorded.svg
  src/Router.svelte
  src/dataSources/api.that.tech/events/queries.js
  src/routes/activities/CallForCounselors.svelte
  src/routes/activities/components/cfp/_CTA.svelte
  src/routes/activities/components/cfp/_EventMeta.svelte
  src/routes/activities/components/cfp/_FAQ.svelte
  src/routes/activities/components/cfp/_Perks.svelte
  src/routes/events/Event.svelte
Labels: Release, WIP

#739 updates activity form to add back tags and resources to open spaces
  src/routes/activities/components/_Steps.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Attributes.svelte
  src/routes/activities/components/form/_Tags.svelte
  src/routes/activities/components/form/_When.svelte
  src/routes/activities/components/form/schemas.js
Labels: bug, critical

#740 adds cfp links to event page
  src/components/cta/_CallForSpeakers.svelte
  src/dataSources/api.that.tech/events/queries.js
  src/elements/buttons/Shell.svelte
  src/elements/links/StandardScroll.svelte
  src/routes/events/components/_Hybrid.svelte
  src/routes/events/components/hybrid/_Hero.svelte
Labels: enhancement

#741 Brett did it.
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/sessions/queries.js
Labels: bug, critical

#742 adds homepage cta for cfp
  src/components/cta/_HomePageCFP.svelte
  src/components/home/Hero.svelte
Labels: enhancement

#744 ticket allocations and transfers
  src/dataSources/api.that.tech/orders/mutations.js
  src/dataSources/api.that.tech/orders/queries.js
  src/routes/communities/Communities.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/my/components/_TicketAllocation.svelte
  src/routes/my/components/_Tickets.svelte
  src/routes/my/machines/bulkAllocations.js
Labels: enhancement
