Repository ThatConference/that.us, pull requests merged in 2021-10, with the labels that each got.

#992 Adds blog and migrated posts
  mdsvex.config.js
  package-lock.json
  package.json
  src/_blog/getPosts.js
  src/_blog/info.js
  src/_dataSources/api.that.tech/members/queries.js
  src/routes/api/rss.json.js
  src/routes/blog/_components/blogCard.svelte
  src/routes/blog/_components/buttonLink.svelte
  src/routes/blog/index.svelte
  src/routes/blog/posts/[slug].svelte
  src/routes/blog/rss.xml.js
  static/blog/posts/2019-cs-ed-week/grace-hopper.png
  static/blog/posts/2019-cs-ed-week/hero.png
  static/blog/posts/2019-cs-ed-week/index.md
  static/blog/posts/2019-happy-holidays/hero.png
  static/blog/posts/2019-happy-holidays/index.md
  static/blog/posts/2020-submission-fields/index.md
  static/blog/posts/2020-submission-fields/that-workstation.jpg
  static/blog/posts/2020-that-online-tickets-available/THAT-Registration-2019.jpg
  static/blog/posts/2020-that-online-tickets-available/index.md
  static/blog/posts/WI-2020-call-for-counselors-open/clark-2019-stage-pointing.jpg
  static/blog/posts/WI-2020-call-for-counselors-open/index.md
  static/blog/posts/april-2020-update/index.md
  static/blog/posts/april-2020-update/that-blog-april-update-2020.jpg
  static/blog/posts/april-2021-recap/index.md
  static/blog/posts/april-2021-recap/thattrees_red.png
  static/blog/posts/celebrating-black-history-month/anjuan-THAT-keynote-2019.jpg
  static/blog/posts/celebrating-black-history-month/index.md
  static/blog/posts/introducing-that-dot-us/heroImage.png
  static/blog/posts/introducing-that-dot-us/index.md
  static/blog/posts/its-time-we-chat/hero.png
  static/blog/posts/its-time-we-chat/index.md
  static/blog/posts/load-the-board-keynotes-announced/index.md
  static/blog/posts/load-the-board-keynotes-announced/load-the-board-keynotes-announced.jpg
  static/blog/posts/refactoring-THAT-conference-2020/index.md
  static/blog/posts/refactoring-THAT-conference-2020/refactoring-THAT-conference-2020.jpg
  static/blog/posts/that-2019-holiday-buying-guide/hero.png
  static/blog/posts/that-2019-holiday-buying-guide/index.md
  static/blog/posts/that-online-recap-that-board-is-officially-open/index.md
  static/blog/posts/that-online-recap-that-board-is-officially-open/that-2020-logo.png
  static/blog/posts/that-year-a-retrospective/index.md
  static/blog/posts/that-year-a-retrospective/that-2020-logo.png
  static/blog/posts/turning-your-awesome-into-submissions/counselor-badges.jpg
  static/blog/posts/turning-your-awesome-into-submissions/index.md
  static/blog/posts/wi-2021-call-for-counselors/index.md
  static/blog/posts/wi-2021-call-for-counselors/that-logo-states-wi-2021.svg
  static/blog/posts/wi-2021-tickets-on-sale/index.md
  static/blog/posts/wi-2021-tickets-on-sale/that-logo-states-wi-2021.svg
  static/blog/posts/womens-day-2020/index.md
  static/blog/posts/womens-day-2020/womens-day-2020.png
  static/favicon.ico
  svelte.config.js
Labels: enhancement

#991 300 - only show activity duration if provided
  src/_components/activities/ActivityDetails.svelte
Labels: enhancement, hacktoberfest

#996 Takes out pre-rendering on blog
  package-lock.json
  package.json
  src/routes/blog/index.svelte
  src/routes/blog/posts/[slug].svelte
Labels: bug, debugging

#997 fixes up some button jank
  src/routes/events/_components/hybrid/_Hero.svelte
Labels: bug

#999 fix formatting for schedule button on Hybrid event pages
  src/routes/events/_components/hybrid/_Hero.svelte
Labels: hacktoberfest, ui/ux

#1070 loading jitsi earlier
  src/routes/join/[activityId]/__layout.svelte
  src/routes/join/[activityId]/index.svelte
Labels: bug

#1072 updates __error logging and fixes 404 on activites
  package.json
  src/routes/__error.svelte
  src/routes/activities/[activity]/index.svelte
Labels: bug

#1073 adds slack icon to socials
  src/_components/footer/socials.js
  src/_components/social/SocialLink.svelte
Labels: enhancement

#1074 updates error object
  src/routes/__error.svelte
Labels: bug
