Repository ThatConference/that.us, pull requests merged in 2021-04, with the labels that each got.

#664 Fixes hero button typos
  src/components/home/Hero.svelte
Labels: bug

#670 enables new access api usage.
  src/dataSources/api.that.tech/events/queries.js
  src/routes/activities/components/form/_Event.svelte
  src/routes/join/Live.svelte
Labels: bug

#673 closes #672
  src/routes/orders/Success.svelte
Labels: enhancement

#674 fixing up some logging issues
  src/App.svelte
  src/main.js
  src/utilities/error.js
Labels: enhancement

#678 adding event logos to listing page
  src/dataSources/api.that.tech/events/queries.js
  src/routes/events/components/_EventCard.svelte
Labels: bug

#675 adding form integration for tickets
  src/Router.svelte
  src/elements/modals/NoAction.svelte
  src/routes/orders/ThatSuccess.svelte
  src/routes/orders/components/_QuestionModal.svelte
Labels: WIP, enhancement

#686 copy updates, refactored footer, links to membership
  src/components/Footer.svelte
  src/components/footer/Footer.svelte
  src/components/footer/links.js
  src/components/footer/socials.js
  src/components/home/CTA.svelte
  src/components/home/CtaMembership.svelte
  src/components/home/Hero.svelte
  src/components/home/NewMembers.svelte
  src/components/home/Testimonials.svelte
  src/components/home/index.js
  src/components/index.js
  src/components/members/Hero.svelte
  src/components/nav/mainNav/Desktop.svelte
  src/dataSources/api.that.tech/me.js
  src/elements/layouts/ContentLayout.svelte
  src/elements/layouts/LandingLayout.svelte
  src/elements/layouts/_BaseContent.svelte
  src/routes/home/Home.svelte
  src/routes/home/components/_WelcomeBack.svelte
  src/routes/membership/components/pricing/_Hero.svelte
Labels: enhancement, ui/ux

#688 closes #680
  src/components/activities/Card.svelte
Labels: enhancement, ui/ux

#689 closes #635
  src/components/activities/ActivityDetails.svelte
  src/dataSources/api.that.tech/sessions.js
  src/elements/Avatars.svelte
Labels: enhancement, ui/ux

#691 accounts for uses with incomplete profiles
  .node-version
  package-lock.json
  package.json
  src/components/home/Testimonials.svelte
  src/components/members/Hero.svelte
  src/routes/home/Home.svelte
Labels: bug, critical

#692 fixed layers on CTA
  src/routes/membership/components/pricing/_NotReady.svelte
Labels: bug

#695 updates join for keynote to be based on location
  src/components/activities/KeynoteCard.svelte
  src/components/activities/KeynoteSpeaker.svelte
  src/dataSources/api.that.tech/sessions.js
Labels: enhancement

#699 soft launch fixes
  package.json
  public/_releaseNotes/1.9.1.aml
  public/_releaseNotes/manifest.aml
  src/dataSources/api.that.tech/orders/mutations.js
  src/main.js
  src/routes/orders/ThatSuccess.svelte
  src/routes/orders/components/_Cart.svelte
Labels: bug

#701 fixes eventId being overwritten with undefined
  src/routes/orders/components/_CartItem.svelte
  src/utilities/cart/cartMachine.js
Labels: bug, critical
