Repository ThatConference/that.us, pull requests merged in 2021-07, with the labels that each got.

#796 fixes #746
  src/routes/my/components/_Badges.svelte
Labels: bug

#797 updates scrolling threshold
  src/components/ScrollThreshold.svelte
  src/routes/activities/Daily.svelte
  src/routes/activities/Event.svelte
  src/routes/communities/Communities.svelte
  src/routes/members/Members.svelte
  src/routes/my/components/_OrderHistory.svelte
  src/routes/partners/EventPartners.svelte
  src/routes/partners/Partners.svelte
Labels: enhancement

#798 Typo fix
  src/components/footer/links.js
Labels: bug

#800 added new questions
  src/routes/promo/components/_FAQ.svelte
  src/routes/promo/components/_Hero.svelte
Labels: enhancement

#801 keynote cards, cta on home page
  src/components/activities/KeynoteCard.svelte
  src/components/activities/List.svelte
  src/components/activities/PanelSpeakers.svelte
  src/components/cta/_TicketsOnSale.svelte
  src/components/home/Hero.svelte
  src/routes/events/components/tickets/_Hero.svelte
Labels: bug, enhancement

#802 minor updates to keynote cards
  src/components/activities/KeynoteCard.svelte
  src/routes/activities/Activity.svelte
Labels: enhancement, ui/ux

#803 removing console statement
  src/routes/promo/Promo.svelte
Labels: bug, chore

#806 refactor partners, added analytics
  public/index.html
  src/App.svelte
  src/routes/partners/Partner.svelte
  src/routes/partners/components/_CTA.svelte
  src/routes/partners/components/_FeaturedMembers.svelte
  src/routes/partners/components/_Followers.svelte
  src/routes/partners/components/_Goals.svelte
  src/routes/partners/components/_Hero.svelte
  src/routes/partners/components/_PartnerCore.svelte
Labels: bug, enhancement

#807 fixes null profile
  src/components/activities/ActivityForm.svelte
  src/components/nav/_UserProfile.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/my/components/_Badges.svelte
  src/routes/my/components/_MembershipSettings.svelte
Labels: bug, critical

#808 better object check
  src/App.svelte
Labels: bug

#810 updates tido user check
  src/App.svelte
Labels: bug

#811 closes #794
  src/components/my/ProfileForm.svelte
Labels: enhancement

#812 updates session details page
  src/components/activities/ActivityDetails.svelte
  src/dataSources/api.that.tech/sessions.js
  src/routes/activities/Activity.svelte
Labels: enhancement

#813 fixes some janky layout
  src/components/activities/ActivityDetails.svelte
Labels: bug

#815 Cs/checkin
  package-lock.json
  package.json
  src/App.svelte
  src/Router.svelte
  src/components/numberPad/Panel.svelte
  src/components/numberPad/PanelButton.svelte
  src/dataSources/api.that.tech/checkin/mutations.js
  src/dataSources/api.that.tech/checkin/queries.js
  src/dataSources/api.that.tech/community/queries.js
  src/dataSources/api.that.tech/events/queries.js
  src/dataSources/api.that.tech/members/queries.js
  src/dataSources/api.that.tech/partner/queries.js
  src/dataSources/api.that.tech/sessions.js
  src/dataSources/api.that.tech/sessions/queries.js
  src/elements/Toggle.svelte
  src/routes/NotFound.svelte
  src/routes/event/Checkin.svelte
  src/routes/event/components/_CheckinModal.svelte
  src/routes/event/components/_EditCheckInModal.svelte
  src/routes/event/components/_Loading.svelte
  src/routes/event/components/_Order.svelte
  src/routes/event/components/_OrderView.svelte
  src/routes/event/components/_RegistrationList.svelte
  src/routes/event/components/_SemiCircle.svelte
  src/routes/event/components/_Ticket.svelte
  src/routes/event/components/_TicketView.svelte
  src/routes/partners/components/_FeaturedMembers.svelte
Labels: chore, enhancement

#817 now sets the fiel on mount such that the form is set right
  src/routes/activities/components/form/components/_AdditionalResources.svelte
  src/routes/activities/components/form/components/_TakeAways.svelte
Labels: bug, critical

#818 fixes bugs around click propagation and toggle view
  src/elements/Toggle.svelte
  src/routes/event/components/_Ticket.svelte
Labels: bug

#819 updates the toggle transformation
  src/elements/Toggle.svelte
Labels: bug

#820 refactors profiles
  src/Router.svelte
  src/components/activities/ActivityForm.svelte
  src/components/nav/_MobileUsersProfile.svelte
  src/components/nav/_UserProfile.svelte
  src/components/nav/interiorNav/Mobile.svelte
  src/components/nav/mainNav/Mobile.svelte
  src/components/notifications/CreateProfile.svelte
  src/components/notifications/NoProfile.svelte
  src/dataSources/api.that.tech/me/mutations.js
  src/dataSources/api.that.tech/me/queries.js
  src/dataSources/api.that.tech/partner/queries.js
  src/elements/Toggle.svelte
  src/routes/Signup.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/join/Live.svelte
  src/routes/my/Profiles.svelte
  src/routes/my/Settings.svelte
  src/routes/my/components/profiles/ProfileForm.svelte
  src/routes/my/components/profiles/_Profile.svelte
  src/routes/my/components/profiles/_SharedProfile.svelte
  src/routes/my/components/profiles/_SharedProfileForm.svelte
  src/routes/orders/components/_Steps.svelte
  src/routes/partners/machines/partners.js
  src/routes/speakers/Accept.svelte
  src/routes/support/CreateAnActivity.svelte
  src/routes/support/Welcome.svelte
Labels: bug, critical, enhancement, ui/ux

#824 Lead List, Verification
  src/Router.svelte
  src/components/nav/_MobileUsersProfile.svelte
  src/components/nav/_UserProfile.svelte
  src/dataSources/api.that.tech/me/network/queries.js
  src/routes/VerifyAccount.svelte
  src/routes/my/Network.svelte
  src/routes/my/components/network/_Sponsors.svelte
Labels: enhancement

#825 Partner Network
  src/Router.svelte
  src/dataSources/api.that.tech/partner/leads/queries.js
  src/routes/my/components/network/_Sponsors.svelte
  src/routes/partners/MyNetwork.svelte
Labels: enhancement

#829 enable open space addition
  src/dataSources/api.that.tech/partner/queries.js
  src/routes/activities/Create.svelte
  src/routes/activities/Edit.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/activities/components/form/_Event.svelte
  src/routes/my/components/network/_Sponsors.svelte
  src/routes/partners/MyNetwork.svelte
  src/routes/partners/Partner.svelte
Labels: enhancement

#832 fixes logic around open space submissions on hybrid events
  src/dataSources/api.that.tech/sessions/mutations.js
  src/routes/activities/components/form/ActivityForm.svelte
Labels: bug

#835 fixes references
  src/components/activities/Card.svelte
Labels: bug, critical

#836 fixes safari
  src/components/activities/Card.svelte
  src/components/activities/List.svelte
Labels: bug

#839 adds timezone
  src/components/activities/ActivityDetails.svelte
  src/components/activities/ActivityForm.svelte
  src/components/cta/_CallForSpeakers.svelte
  src/components/home/Event.svelte
  src/elements/FeaturedActivity.svelte
  src/elements/FeaturedActivityDetail.svelte
  src/routes/activities/components/cfp/_CTA.svelte
  src/routes/activities/components/form/_When.svelte
  src/routes/activities/components/form/components/_EventNoAccess.svelte
  src/routes/event/components/_Ticket.svelte
  src/routes/events/components/online/_EventTicket.svelte
Labels: enhancement

#840 clears text area
  src/routes/partners/Leads.svelte
Labels: bug, enhancement

#842 Cs/partner download
  src/dataSources/api.that.tech/partner/leads/queries.js
  src/routes/partners/MyNetwork.svelte
  src/utilities/csv.js
Labels: enhancement

#844 updates date inbetween check
  src/routes/activities/components/form/_Event.svelte
Labels: bug

#847 CFP for TX, package & package bumps
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/cta/_HomePageCFP.svelte
  src/components/home/Hero.svelte
  tailwind.config.js
Labels: chore
