Repository ThatConference/that.us, pull requests merged in 2021-08, with the labels that each got.

#850 Activity Form Hybrid Selection startDate endDate
  src/routes/activities/components/form/ActivityForm.svelte
Labels: bug, critical

#855 account verification, stripe and profile bug
  public/index.html
  src/Router.svelte
  src/routes/VerifyAccount.svelte
  src/routes/my/Profiles.svelte
  src/routes/my/components/profiles/_SharedProfile.svelte
  src/routes/orders/Summary.svelte
Labels: bug

#858 updates layout to fix hidden profile menu
  src/elements/layouts/_BaseContent.svelte
  src/elements/layouts/_NavWrapper.svelte
Labels: bug, ui/ux

#852 Adding additional clarification that times are in local timezones
  src/routes/activities/Daily.svelte
  src/routes/activities/Event.svelte
  src/routes/activities/components/form/ActivityForm.svelte
  src/routes/support/CreateAnActivity.svelte
  src/routes/support/JoiningAnActivity.svelte
Labels: enhancement, ui/ux

#859 adds tz to the header values
  src/components/activities/List.svelte
  src/routes/activities/Daily.svelte
  src/routes/activities/Event.svelte
Labels: enhancement, ui/ux

#582 Issue 417
  src/routes/my/components/profiles/ProfileForm.svelte
Labels: enhancement, hold

#860 adds markdown support and missing legal pages
  package-lock.json
  package.json
  rollup.config.js
  src/Router.svelte
  src/components/footer/links.js
  src/elements/layouts/markdown/Support.svelte
  src/elements/layouts/markdown/_Header.svelte
  src/routes/my/components/profiles/ProfileForm.svelte
  src/routes/support/Anti-Harassment-Policy.md
  src/routes/support/Code-Of-Conduct.md
  src/routes/support/Commitment-To-Diversity.md
  src/routes/support/Copyright.md
  src/routes/support/Privacy-Policy.md
  src/routes/support/Terms-Of-Use.md
Labels: bug, enhancement
