Repository ThatConference/that.us, pull requests merged in 2021-12, with the labels that each got.

#1100 fixed partner featured session
  src/_dataSources/api.that.tech/partner/queries.js
  src/routes/partners/[partner]/index.svelte
Labels: bug

#1101 updates how we pull og-image for activites
  src/_utils/seo/metaTags.js
  src/routes/activities/[activity]/index.svelte
  src/routes/api/og-image/[id].js
  static/images/ActivityDefault.jpg
Labels: enhancement

#1102 swaps fetch
  src/routes/api/og-image/[id].js
Labels: bug

#1103 swaps buffer
  src/routes/api/og-image/[id].js
Labels: bug

#1105 make urls correct
  src/_utils/image.js
Labels: bug

#1109 updates gfetch to only retry 5 times
  src/_utils/gfetch.js
Labels: bug, critical

#1110 removes typo
  src/_dataSources/api.that.tech/checkin/queries.js
Labels: bug

#1093 Removed console warnings for FeaturedActivity
  src/_components/activities/UpNext.svelte
  src/_components/activities/UpNextEvent.svelte
  src/routes/_root/components/upNext.svelte
  src/routes/communities/[community]/_components/upNext.svelte
Labels: chore

#1106 Fixes local issue with svelte-awesome and adblocker
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/FilterSlideOver.svelte
  src/_components/activities/KeynoteCard.svelte
  src/_components/activities/List.svelte
  src/_components/activities/elements/CalendarButton.svelte
  src/_components/activityCenter/ActivitySlideOver.svelte
  src/_components/nav/_MobileUsersProfile.svelte
  src/_components/nav/_UserProfile.svelte
  src/_components/nav/interiorNav/Large.svelte
  src/_components/nav/mainNav/Desktop.svelte
  src/_components/notifications/Error.svelte
  src/_components/notifications/NoProfile.svelte
  src/_components/notifications/Warning.svelte
  src/_components/releaseNotes/Release.svelte
  src/_components/social/SocialLink.svelte
  src/_components/svelte-awesome-icons.js
  src/_elements/FeaturedActivity-Add.svelte
  src/_elements/FeaturedActivityDetail.svelte
  src/_elements/FeaturedActivityLoading.svelte
  src/routes/activities/_components/_Step.svelte
  src/routes/activities/_components/form/_SectionTitle.svelte
  src/routes/activities/clone/index.svelte
  src/routes/activities/create/index.svelte
  src/routes/activities/edit/[activityId].svelte
  src/routes/events/_components/online/_EventTicket.svelte
  src/routes/join/[activityId]/index.svelte
  src/routes/my/profiles/_components/profileForm.svelte
  src/routes/my/settings/_components/ticketAllocation.svelte
  src/routes/my/submissions/_components/submission.svelte
  src/routes/speakers/_components/formSections/AcceptInvitation.svelte
  src/routes/speakers/_components/step.svelte
Labels: bug, enhancement

#1094 Speaker List for an event (WIP?)
  src/_dataSources/api.that.tech/events/queries.js
  src/routes/events/[event]/[date]/index.svelte
  src/routes/events/_components/_Hybrid.svelte
  src/routes/events/_components/_Online.svelte
  src/routes/events/_components/speakers/_Speakers.svelte
Labels: ui/ux

#1112 #779 Added filtering for onThat, atThat, family, open spaces, and workshops
  src/_components/activities/FilterSlideOver.svelte
  src/_components/activities/List.svelte
Labels: enhancement

#1113 1085 - Update the z-index of the footer so the tree SVG is behind the…
  src/_components/footer/Footer.svelte
Labels: bug, ui/ux

#1115 868 Update hybrid event hero h1 div z-index
  src/routes/events/_components/hybrid/_Hero.svelte
Labels: bug, ui/ux

#1118 build: adding release tools
  .github/workflows/release.yml
  .husky/commit-msg
  CHANGELOG.md
  commitlint.config.cjs
  package-lock.json
  package.json
  release.config.cjs
Labels: enhancement, chore

#1119 docs: updated readme
  README.md
Labels: documentation

#1120 fix: updated branch name
  .github/workflows/release.yml
Labels: bug

#1121 fix: updates secrets to push
  .github/workflows/release.yml
Labels: bug

#1122 fix: adding token to checkout step
  .github/workflows/release.yml
Labels: bug

#1123 fix: adding the correct version tag
  package.json
Labels: bug

#1125 chore: add default value in .env.sample file for Stripe private key
  .env.sample
Labels: bug, documentation, chore

#1128 Hybrid - Fix Schedule "button"
  src/routes/events/_components/_Hybrid.svelte
Labels: enhancement

#1129 feat: dense view
  CHANGELOG.md
  src/_components/activities/Card.svelte
  src/_components/activities/CardLink.svelte
  src/_components/activities/List.svelte
Labels: enhancement

#1130 feat: updates default og-images
  .prettierrc
  package.json
  src/_utils/seo/metaTags.js
  src/app.html
  src/routes/blog/posts/__layout.svelte
  static/favicon-og.png
  static/images/og-images/facebook.jpg
  static/images/og-images/linkedIn.jpg
  static/images/og-images/twitter.jpg
  static/images/og-logo.png
Labels: enhancement

#1131 fix: login / logout buttons as rel=external
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/nav/_MobileUsersProfile.svelte
  src/_components/nav/_UserProfile.svelte
  src/_components/nav/mainNav/Mobile.svelte
  src/_elements/links/Standard.svelte
  src/_elements/svgs/Step.svelte
  src/_utils/config.js
  src/routes/communities/[community]/_components/cta.svelte
  src/routes/communities/[community]/_components/hero.svelte
  src/routes/members/_components/cta.svelte
  src/routes/orders/_components/_Steps.svelte
  src/routes/partners/_components/_CTA.svelte
  src/routes/signup.svelte
  src/routes/support/creating-an-activity.svelte
  static/robots.txt
Labels: bug
