Repository ThatConference/that.us, pull requests merged in 2022-03, with the labels that each got.

#1132 fix: attempt to get the changelog entries to match the prettyrc format.
  .prettierignore
Labels: bug

#1211 refactor: event landing
  src/routes/_root/components/hero.svelte
  src/routes/events/_components/_Hybrid.svelte
  src/routes/events/_components/hybrid/Gallery.svelte
  src/routes/events/_components/hybrid/Hero.svelte
  src/routes/events/_components/hybrid/WhatIs.svelte
  src/routes/events/_components/hybrid/_What.svelte
  static/images/characters/drone.svg
  static/images/characters/red-bear.svg
  static/images/characters/sassy.svg
  static/images/event-highlight.jpg
  static/images/faux-ticket-stub.svg
  static/images/gallery/51381190522.jpg
  static/images/gallery/51381193527.jpg
  static/images/gallery/51381371307.jpg
  static/images/gallery/51381373422.jpg
  static/images/gallery/51381395922.jpg
  static/images/gallery/51381956911.jpg
  static/images/gallery/51381960426.jpg
  static/images/gallery/51382132986.jpg
  static/images/gallery/51382159251.jpg
  static/images/gallery/51382204938.jpg
  static/images/gallery/51382387343.jpg
  static/images/gallery/51382392593.jpg
  static/images/gallery/51382398568.jpg
  static/images/gallery/51382399928.jpg
  static/images/gallery/51382697849.jpg
  static/images/gallery/51382698379.jpg
  static/images/gallery/51382864699.jpg
  static/images/gallery/51382962890.jpg
  static/images/gallery/51382972555.jpg
  static/images/gallery/51383136300.jpg
  static/images/video-preview.jpg
Labels: enhancement, ui/ux

#1212 feat: new event nav and cleanup
  src/_components/SponsorSimple.svelte
  src/_components/blog/latest.svelte
  src/_components/events/layouts/hybrid/Layout.svelte
  src/_components/events/layouts/hybrid/nav/EventNav.svelte
  src/_components/events/layouts/hybrid/nav/MobileEventNav.svelte
  src/_components/events/layouts/hybrid/nav/MobileNavHat.svelte
  src/_components/events/layouts/hybrid/nav/Nav.svelte
  src/_components/events/layouts/hybrid/nav/NavHat.svelte
  src/_components/events/layouts/hybrid/nav/components/navLink.svelte
  src/_components/events/thatconference/_components/Layout.svelte
  src/_components/faq/FaqItem.svelte
  src/_components/nav/AddActivity.svelte
  src/_components/nav/Cart.svelte
  src/_components/nav/MobileUsersProfile.svelte
  src/_components/nav/UserProfile.svelte
  src/_components/nav/interiorNav/Large.svelte
  src/_components/nav/interiorNav/Mobile.svelte
  src/_components/nav/mainNav/Desktop.svelte
  src/_components/nav/mainNav/Mobile.svelte
  src/_dataSources/api.that.tech/partner/queries.js
  src/_elements/buttons/Shell.svelte
  src/_elements/buttons/StandardShell.svelte
  src/_elements/buttons/index.js
  src/_elements/svgs/LeftArrow.svelte
  src/_elements/svgs/Plus.svelte
  src/_elements/svgs/RightArrow.svelte
  src/_elements/svgs/illustrations/Code.svelte
  src/routes/__layout.svelte
  src/routes/_root/components/events.svelte
  src/routes/_root/components/newMembers.svelte
  src/routes/_root/components/stats.svelte
  src/routes/_root/components/upNext.svelte
  src/routes/activities/_components/form/_SectionTitle.svelte
  src/routes/event/check-in/_components/_CheckinModal.svelte
  src/routes/event/check-in/_components/_OrderView.svelte
  src/routes/event/check-in/_components/_TicketView.svelte
  src/routes/events/[event]/[date]/schedule.svelte
  src/routes/events/[event]/[date]/sponsors.svelte
  src/routes/events/[event]/[date]/tickets.svelte
  src/routes/events/[event]/[date]/travel.svelte
  src/routes/events/_components/_Hybrid.svelte
  src/routes/events/_components/_MembershipCard.svelte
  src/routes/events/_components/_MultiDay.svelte
  src/routes/events/_components/hybrid/CamperTickets.svelte
  src/routes/events/_components/hybrid/FAQ.svelte
  src/routes/events/_components/hybrid/Gallery.svelte
  src/routes/events/_components/hybrid/Partners.svelte
  src/routes/events/_components/hybrid/What.svelte
  src/routes/events/_components/hybrid/_Hero.svelte
  src/routes/events/_components/hybrid/dates.svelte
  src/routes/events/_components/tickets/_Hero.svelte
  src/routes/link-tree/index.svelte
  src/routes/membership/_components/pricing/_EventTickets.svelte
  src/routes/my/settings/_components/ticketAllocation.svelte
  src/routes/orders/_components/_CartItem.svelte
  src/routes/partners/[state]/[year].svelte
  src/routes/partners/_components/_Hero.svelte
  src/routes/partners/leads/[eventId].svelte
  src/routes/support/travel/index.svelte
  static/images/ThatConferenceLogo.svg
Labels: enhancement, ui/ux, new

#1214 chore: update sitemap
  static/sitemap.xml
Labels: chore

#1213 fix: fixes button and removes console
  src/routes/_root/components/hero.svelte
  src/routes/partners/[state]/[year].svelte
Labels: bug

#1216 fix: incorrect url
  src/routes/events/_components/_Hybrid.svelte
  src/routes/events/_components/hybrid/WhatIs.svelte
Labels: bug

#1217 refactor: add 'id' to datasources for reference by graphCDN
  src/_dataSources/api.that.tech/community/queries.js
  src/_dataSources/api.that.tech/events/queries.js
  src/_dataSources/api.that.tech/me/network/queries.js
  src/_dataSources/api.that.tech/me/queries.js
  src/_dataSources/api.that.tech/members/mutations.js
  src/_dataSources/api.that.tech/members/queries.js
  src/_dataSources/api.that.tech/orders/mutations.js
  src/_dataSources/api.that.tech/orders/queries.js
  src/_dataSources/api.that.tech/partner/leads/queries.js
  src/_dataSources/api.that.tech/partner/queries.js
  src/_dataSources/api.that.tech/products/queries.js
  src/_dataSources/api.that.tech/sessions.js
  src/_dataSources/api.that.tech/speakers/queries.js
  src/_dataSources/api.that.tech/submissions.js
Labels: chore

#1218 fix: fix url refs with activity, should be activities
  src/_utils/ical.js
  src/routes/activities/[activity]/index.svelte
  src/routes/activities/edit/[activityId].svelte
  src/routes/support/creating-an-activity.svelte
Labels: bug
