Repository ThatConference/that.us, pull requests merged in 2022-01, with the labels that each got.

#1133 New default images for root paths.
  src/_utils/seo/metaTags.js
  src/routes/activities/index.svelte
  src/routes/blog/index.svelte
  src/routes/communities/index.svelte
  src/routes/events/index.svelte
  src/routes/members/index.svelte
  src/routes/partners/index.svelte
  src/routes/support/index.svelte
  static/images/og-images/activities-Facebook.jpg
  static/images/og-images/activities-LinkedIn.jpg
  static/images/og-images/activities-Twitter.jpg
  static/images/og-images/blog-Facebook.jpg
  static/images/og-images/blog-LinkedIn.jpg
  static/images/og-images/blog-Twitter.jpg
  static/images/og-images/communities-Facebook.jpg
  static/images/og-images/communities-LinkedIn.jpg
  static/images/og-images/communities-Twitter.jpg
  static/images/og-images/events-Facebook.jpg
  static/images/og-images/events-LinkedIn.jpg
  static/images/og-images/events-Twitter.jpg
  static/images/og-images/help-Facebook.jpg
  static/images/og-images/help-LinkedIn.jpg
  static/images/og-images/help-Twitter.jpg
  static/images/og-images/members-Facebook.jpg
  static/images/og-images/members-LinkedIn.jpg
  static/images/og-images/members-Twitter.jpg
  static/images/og-images/sponsors-Facebook.jpg
  static/images/og-images/sponsors-LinkedIn.jpg
  static/images/og-images/sponsors-Twitter.jpg
Labels: enhancement

#1134 refactor: updating page titles
  src/routes/activities/[activity]/index.svelte
  src/routes/activities/[state]/[year]/index.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/activities/create/index.svelte
  src/routes/activities/index.svelte
  src/routes/blog/index.svelte
  src/routes/blog/posts/__layout.svelte
  src/routes/call-for-counselors/index.svelte
  src/routes/communities/[community]/index.svelte
  src/routes/communities/index.svelte
  src/routes/events/[event]/[date]/tickets.svelte
  src/routes/events/index.svelte
  src/routes/index.svelte
  src/routes/join/access-denied.svelte
  src/routes/members/index.svelte
  src/routes/membership/index.svelte
  src/routes/partners/[partner]/index.svelte
  src/routes/partners/[partner]/jobs/[job].svelte
  src/routes/partners/[state]/[year].svelte
  src/routes/partners/index.svelte
  src/routes/partners/past/index.svelte
  src/routes/signup.svelte
  src/routes/support/what-is-an-activity.svelte
  src/routes/verify-account.svelte
Labels: enhancement

#1136 fix: auth wrapper login redirect
  src/_utils/security/auth.js
Labels: bug

#1137 fix: security config paths wrong
  .env.sample
  src/_utils/security/auth.js
Labels: bug

#1138 fix: adds a login redirect for dynamic logins
  src/_utils/security/auth.js
  src/routes/login-redirect.svelte
Labels: bug

#1139 feat: adding googles structured data
  src/_dataSources/api.that.tech/events/queries.js
  src/app.html
  src/routes/events/_components/_Hybrid.svelte
  static/sitemap.xml
  static/that-logo.jpg
  static/that-logo.png
  svelte.config.js
Labels: seo, new

#1140 adds ld+json for job postings, that online and blog posts.
  src/_dataSources/api.that.tech/partner/queries.js
  src/routes/blog/posts/__layout.svelte
  src/routes/events/_components/_Hybrid.svelte
  src/routes/events/_components/_Online.svelte
  src/routes/partners/[partner]/jobs/[job].svelte
Labels: enhancement, seo, new

#1141 refactor: updates passkey links
  src/_utils/config.js
Labels: chore

#1143 refactor: double if
  .github/workflows/release-success.yml
Labels: chore

#1144 fix: robots to allow google to index page assets
  static/robots.txt
Labels: bug

#1145 fix: updating account verification message
  src/_components/nav/_MobileUsersProfile.svelte
  src/routes/verify-account.svelte
Labels: bug

#1147 refactor: updates dates and adds redirect page
  src/_utils/config.js
  src/routes/support/travel/tx.svelte
  src/routes/support/travel/wi.svelte
  src/routes/tx.svelte
  src/routes/wi.svelte
Labels: enhancement

#1148 fix: dates are hard
  src/_utils/config.js
Labels: bug

#1151 refactor: footer links
  src/_components/footer/Footer.svelte
  src/_components/footer/Newsletter.svelte
  src/_components/footer/links.js
Labels: enhancement

#1155 refactor: adds newsletter to signup page
  src/_components/footer/Footer.svelte
  src/_components/footer/links.js
  src/_components/newsletter/Footer.svelte
  src/_components/newsletter/Short.svelte
  src/_components/newsletter/Wide.svelte
  src/_components/newsletter/_form.js
  src/routes/_root/components/index.js
  src/routes/blog/posts/__layout.svelte
  src/routes/orders/success/__layout.svelte
  src/routes/signup.svelte
Labels: enhancement

#1156 feat: adds community curated news submission
  src/_dataSources/api.that.tech/news/mutations.js
  src/routes/news/__layout.svelte
  src/routes/news/_components/submitForm.svelte
  src/routes/news/submit.svelte
Labels: new

#1157 refactor: updates sitemap
  package.json
  static/sitemap.xml
Labels: enhancement, chore

#1159 feat: adds microsoft clarity
  src/app.html
  src/routes/join/[activityId]/__layout.svelte
Labels: new

#1158 fix: announcemnts typo to announcements
  src/_components/blog/latest.svelte
  src/routes/blog/index.svelte
Labels: bug

#1161 refactor: covid updates
  src/_components/footer/links.js
  src/routes/support/covid-policies.svelte
Labels: enhancement

#1162 refactor: fixed spelling mistake
  src/routes/events/index.svelte
Labels: bug

#1164 refactor: updated travel pages to include hotel pricing
  src/routes/support/travel/tx.svelte
  src/routes/support/travel/wi.svelte
Labels: enhancement

#1167 fix: incorrect logout path
  src/_components/nav/_UserProfile.svelte
Labels: bug

#1165 feat: edge cache and preconnect
  src/_components/activities/Card.svelte
  src/_components/activities/CardLink.svelte
  src/_utils/config.js
Labels: new

#1170 refactor: bug fixes, performance, refactoring
  src/_components/activities/Card.svelte
  src/_components/activities/UpNextEvent.svelte
  src/_components/blog/components/blogCard.svelte
  src/_components/footer/Footer.svelte
  src/_components/members/MemberCard.svelte
  src/_components/nav/_UserProfile.svelte
  src/_components/nav/interiorNav/Large.svelte
  src/_components/nav/interiorNav/Mobile.svelte
  src/_components/nav/mainNav/Desktop.svelte
  src/_components/nav/mainNav/MainNav.svelte
  src/_elements/FeaturedActivity.svelte
  src/routes/_root/components/events.svelte
  src/routes/events/_components/Notices.svelte
  src/routes/events/_components/hybrid/_CamperTickets.svelte
  src/routes/events/_components/hybrid/_Hero.svelte
  src/routes/events/_components/speakers/_Speakers.svelte
  src/routes/events/_components/tickets/_Families.svelte
  src/routes/events/_components/tickets/_Hero.svelte
  src/routes/events/_components/tickets/_Workshops.svelte
  src/routes/news/submit.svelte
  src/routes/that-conference.svelte
Labels: bug, enhancement

#1171 fix: missing rel attribute
  src/_components/nav/_UserProfile.svelte
Labels: bug, critical

#1172 fix: adding csp
  src/app.html
Labels: bug, critical

#1173 fix: removing csp
  src/app.html
Labels: bug
