Repository ThatConference/that.us, pull requests merged in 2022-11, with the labels that each got.

#1332 feat: finishes apply now
  package-lock.json
  src/_blog/posts/2019-happy-holidays/index.md
  src/_blog/posts/april-2021-recap/index.md
  src/_components/SponsorSimple.svelte
  src/_components/nav/thatConference/EventNav.svelte
  src/routes/events/(thatConferences)/_components/nav/EventNav.svelte
  src/routes/events/_components/sponsors/Hero.svelte
  src/routes/partners/_components/_EventHero.svelte
  src/routes/partners/_components/_PartnersHero.svelte
  src/routes/sponsorships/apply/+page.js
  src/routes/sponsorships/apply/+page.svelte
  src/routes/sponsorships/apply/ticker.svelte
  static/images/characters/skinny.svg
  static/images/sponsorship-packages.png
Labels: enhancement

#1334 chore: fixes intellisense
  jsconfig.json
Labels: chore

#1335 chore: updates sitemap
  static/sitemap.xml
Labels: chore

#1337 chore: change profile image upload url
  src/_utils/config.public.js
Labels: chore

#1339 chore: adding twitter integration
  src/app.html
Labels: chore

#1340 chore: remove twitter integration
  src/app.html
Labels: chore

#1341 fix: fix my favorites from api change a few weeks back
  .env.sample
  src/routes/my/favorites/+page.js
Labels: bug

#1342 feat: adding a shortcut link to member profile
  src/routes/m/[member]/+page.js
  src/routes/m/[member]/+page.svelte
Labels: new
