Repository ThatConference/that.us, pull requests merged in 2022-02, with the labels that each got.

#1174 fix: removing prefetch from user menu
  src/_components/nav/_UserProfile.svelte
Labels: bug

#1176 caching issues and bug fixes
  src/_elements/modals/Error.svelte
  src/_utils/config.js
  src/_utils/gfetch.js
  src/_utils/gtag.js
  src/app.html
  src/hooks/index.js
  src/routes/__layout.svelte
  src/routes/api/auth/callback.js
  src/routes/api/auth/proxy.js
  src/routes/event/check-in/_components/_CheckinModal.svelte
  src/routes/event/check-in/_components/_EditCheckInModal.svelte
  src/routes/my/profiles/_components/emergencyContactForm.svelte
  src/routes/partners/leads/[eventId].svelte
Labels: bug, critical

#1181 fix: 1178
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/login-redirect.svelte
  src/routes/orders/success/index.svelte
  src/routes/promo/index.svelte
Labels: bug

#1182 fix: closes #1179
  src/_utils/security/auth.js
Labels: bug

#1183 fix: cleaned up load params and url
  src/routes/activities/[activity]/index.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/members/[member]/index.svelte
  src/routes/speakers/accept/index.svelte
Labels: bug

#1184 fix: ref wrong object
  src/_utils/security/auth.js
Labels: bug

#1177 fix: package bumps
  .node-version
  jsconfig.json
  package-lock.json
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_utils/config.js
  src/_utils/gfetch.js
  src/_utils/security/auth.js
  src/_utils/security/wrappers.js
  src/hooks/index.js
  src/routes/__error.svelte
  src/routes/activities/[activity]/index.svelte
  src/routes/activities/[state]/[year]/__layout.svelte
  src/routes/activities/clone/__layout.svelte
  src/routes/activities/create/__layout.svelte
  src/routes/activities/create/cfp.svelte
  src/routes/activities/edit/__layout.svelte
  src/routes/api/auth/callback.js
  src/routes/api/auth/me.js
  src/routes/api/auth/proxy.js
  src/routes/blog/posts/__layout.svelte
  src/routes/call-for-counselors/[event]/[year]/index.svelte
  src/routes/communities/[community]/index.svelte
  src/routes/event/check-in/[eventName]/[year]/index.svelte
  src/routes/events/[event]/[date]/index.svelte
  src/routes/events/[event]/[date]/tickets.svelte
  src/routes/events/_components/_Hybrid.svelte
  src/routes/join/[activityId]/index.svelte
  src/routes/login-redirect.svelte
  src/routes/login.js
  src/routes/logout.js
  src/routes/members/[member]/index.svelte
  src/routes/my/network/__layout.svelte
  src/routes/my/profiles/__layout.svelte
  src/routes/my/settings/__layout.svelte
  src/routes/orders/success/index.svelte
  src/routes/partners/[partner]/jobs/[job].svelte
  src/routes/promo/index.svelte
  src/routes/sessions/[id].svelte
  src/routes/speakers/accept/index.svelte
  svelte.config.js
Labels: bug, enhancement, chore

#1185 chore: adds cache purge on CloudFlare on deploy
  .github/workflows/release-success.yml
Labels: chore

#1187 fix: closes #1186, removes clarity
  .node-version
  src/app.html
  src/routes/my/settings/membership.svelte
  src/routes/support/staying-up-to-date.svelte
Labels: bug, chore

#1188 refactor: adds copy attribution
  src/routes/__layout.svelte
Labels: enhancement

#1193 refactor: adds support for external links
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/routes/_root/components/thatConferences.svelte
Labels: enhancement

#1195 refactor: jitsi load, perf loading
  src/_components/svelte-awesome-icons.js
  src/app.html
  src/routes/join/[activityId]/__layout.svelte
  src/routes/join/[activityId]/index.svelte
Labels: enhancement

#1196 Join and gFetch Dynamic Url
  src/_components/activities/ActivityDetails.svelte
  src/_utils/gfetch.js
Labels: bug, critical

#1197 fix: fixing button and anchor attributes
  src/_components/NewFeatureWarning.svelte
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/KeynoteCard.svelte
  src/_components/activities/UpNext.svelte
  src/_components/faq/_FAQ.svelte
  src/_components/nav/_UserProfile.svelte
  src/_components/nav/interiorNav/Large.svelte
  src/_components/nav/interiorNav/Top.svelte
  src/_components/notifications/Success.svelte
  src/_components/notifications/Warning.svelte
  src/_components/numberPad/PanelButton.svelte
  src/_elements/buttons/Highlight.svelte
  src/_elements/buttons/Standard.svelte
  src/_elements/overlays/BasicSlideOver.svelte
  src/routes/_root/components/upNext.svelte
  src/routes/activities/_components/form/components/_AdditionalResources.svelte
  src/routes/activities/_components/form/components/_TakeAways.svelte
  src/routes/activities/edit/[activityId].svelte
  src/routes/event/check-in/_components/_CheckinModal.svelte
  src/routes/event/check-in/_components/_EditCheckInModal.svelte
  src/routes/event/check-in/_components/_Order.svelte
  src/routes/event/check-in/_components/_Ticket.svelte
  src/routes/events/_components/_TicketCard.svelte
  src/routes/events/_components/online/_OnlineHero.svelte
  src/routes/events/_components/tickets/_Professional.svelte
  src/routes/join/[activityId]/index.svelte
  src/routes/my/profiles/slack.svelte
  src/routes/my/settings/order-history.svelte
  src/routes/my/submissions/_components/submission.svelte
  src/routes/partners/leads/[eventId].svelte
  src/routes/partners/my-network/index.svelte
  src/routes/promo/_components/_Hero.svelte
  src/routes/speakers/_components/formSections/AcceptInvitation.svelte
  src/routes/speakers/_components/formSections/AtThatNextSteps.svelte
  src/routes/speakers/_components/formSections/CampsiteComps.svelte
  src/routes/speakers/_components/formSections/DeclineModal.svelte
  src/routes/speakers/_components/formSections/SelectTickets.svelte
  src/routes/speakers/_components/formSections/TicketDetail.svelte
  src/routes/support/staying-up-to-date.svelte
Labels: enhancement

#1198 Refactor: Jitsi Breakout Rooms
  src/_utils/config.js
  src/_utils/security/auth.js
  src/routes/join/[activityId]/index.svelte
Labels: enhancement

#1201 fix: fixes issue #1200
  src/routes/activities/clone/index.svelte
Labels: bug, critical

#1203 fix: backdoor check
  src/routes/activities/create/__layout.svelte
Labels: bug, critical

#1205 refactor: profile spelling
  src/routes/my/profiles/_components/profileForm.svelte
Labels: bug

#1206 refactor: url loading
  src/routes/join/[activityId]/index.svelte
Labels: bug, jitsi
