Repository ThatConference/that.us, pull requests merged in 2022-05, with the labels that each got.

#1239 fix: correct sessions being loaded
  src/routes/events/[event]/[date]/schedule/index.svelte
  src/routes/events/_components/schedule/List.svelte
Labels: bug

#1240 fix: button stacking in hero
  src/routes/events/_components/schedule/Hero.svelte
Labels: bug, ui/ux

#1241 fix: updates nav, and travel
  src/_components/events/layouts/hybrid/nav/EventNav.svelte
  src/_components/events/layouts/hybrid/nav/NavHat.svelte
  src/routes/support/travel/tx.svelte
  src/routes/support/travel/wi.svelte
Labels: bug, ui/ux

#1242 fix: family filter for sessions
  src/_components/activities/FilterSlideOver.svelte
  src/_components/activities/List.svelte
  src/_dataSources/api.that.tech/sessions.js
Labels: bug

#1243 fix: room block date extension
  src/_utils/config.js
Labels: chore

#1244 fix: adds cub
  src/routes/partners/[state]/[year].svelte
Labels: bug

#1245 feat: adds new shared profile fields and updates lead generation
  .node-version
  package-lock.json
  package.json
  src/_dataSources/api.that.tech/me/mutations.js
  src/_dataSources/api.that.tech/me/queries.js
  src/_dataSources/api.that.tech/partner/leads/queries.js
  src/routes/my/profiles/__layout.svelte
  src/routes/my/profiles/_components/sharedProfileForm.svelte
  src/routes/my/profiles/shared.svelte
  src/routes/partners/leads/[eventId].svelte
  src/routes/partners/leads/index.svelte
  src/routes/partners/my-network/index.svelte
Labels: bug, enhancement, chore

#1249 fix: modal on checkin
  src/routes/event/check-in/_components/_CheckinModal.svelte
Labels: bug

#1253 fix: correct wi hotel block close dates
  src/_utils/config.js
Labels: bug

#1254 fix: add disclaimer in speaker enrollment
  src/routes/speakers/_components/formSections/CampsiteComps.svelte
Labels: enhancement
