Repository ThatConference/that.us, pull requests merged in 2023-04, with the labels that each got.

#1371 fix: update emergency contact phone number regex
  package-lock.json
  src/routes/my/profiles/_components/emergencyContactForm.svelte
  src/routes/speakers/_components/formSections/EmergencyContactInfo.svelte
Labels: bug

#1373 fix: adds shared profile to the description
  src/routes/my/notification-preferences/+page.svelte
  src/routes/my/notification-preferences/components/Notification.svelte
Labels: ui/ux

#1374 refactor: add missing trailingSlash entries for svelte v1
  package.json
  src/_components/footer/Footer.svelte
  src/_utils/gfetch.js
  src/routes/+layout.server.js
  src/routes/api/auth/callback/+server.js
  src/routes/api/auth/me/+server.js
  src/routes/api/auth/proxy/+server.js
  src/routes/api/auth/signup/+server.js
  src/routes/api/og-image/[id]/+server.js
  src/routes/api/releases.json/+server.js
  src/routes/login/+server.js
  src/routes/logout/+server.js
Labels: bug, chore

#1375 fix: adds month to event hero just for Mike and THAT Time Machine
  src/routes/events/(thatConferences)/tx/[year]/_components/Hero.svelte
  src/routes/events/(thatConferences)/wi/[year]/_components/Hero.svelte
Labels: ui/ux

#1376 feat: adding user insights
  src/app.html
Labels: new

#1377 feat: adding more user insights again
  src/app.html
Labels: new
