Repository ThatConference/that.us, pull requests merged in 2023-10, with the labels that each got.

#1471 Fix/source maps
  package-lock.json
  package.json
  src/routes/events/(online)/_components/EventTicket.svelte
  vite.config.js
Labels: bug

#1472 promote Next/feature to production
  package-lock.json
  package.json
  src/routes/events/(online)/_components/EventTicket.svelte
  vite.config.js
Labels: bug

#1474 Refactor order success page
  .github/workflows/release-success.yml
  package.json
  src/_elements/links/Standard.svelte
  src/routes/orders/_components/_Cart.svelte
  src/routes/orders/success/+page.svelte
  src/routes/orders/success/claim-ticket/+page.svelte
  src/routes/support/transfer-a-ticket/+page.svelte
Labels: bug, chore

#1475 Promote Next/feature to production
  .github/workflows/release-success.yml
  package.json
  src/_elements/links/Standard.svelte
  src/routes/orders/_components/_Cart.svelte
  src/routes/orders/success/+page.svelte
  src/routes/orders/success/claim-ticket/+page.svelte
  src/routes/support/transfer-a-ticket/+page.svelte
Labels: enhancement, chore

#1479 fix: gfetch - fetch r.ok
  package.json
  src/_utils/gfetch.js
Labels: bug

#1480 feature push
  package.json
  src/_utils/gfetch.js
Labels: bug

#1481 fix: recaptcha undefined
  src/routes/+layout.svelte
Labels: bug

#1483 fix: removing exception catch on retry
  src/_utils/gfetch.js
Labels: bug

#1485 fix: correctly show user isn't assigned to partner
  package.json
  src/_dataSources/api.that.tech/partner/leads/mutations.js
Labels: bug

#1486 Promote Next/feature to production
  package.json
  src/_dataSources/api.that.tech/partner/leads/mutations.js
Labels: bug

#1488 fix: typos in links and activity filter. plus lint requirement
  package.json
  src/_components/activities/List.svelte
  src/_components/footer/links.js
  src/app.html
Labels: bug, chore

#1489 Feat/add svelte auth
  package-lock.json
  package.json
  src/_components/nav/UserProfile.svelte
  src/_components/nav/mainNav/Mobile.svelte
  src/_utils/config.public.js
  src/_utils/security/auth.js
  src/_utils/security/client.js
  src/_utils/security/server.js
  src/_utils/security/svelteAuth/parseJwt.js
  src/_utils/security/wrappers.js
  src/hooks.client.js
  src/hooks.server.js
  src/routes/+layout.server.js
  src/routes/activities/clone/+page.server.js
  src/routes/activities/create/+layout.server.js
  src/routes/activities/edit/+layout.server.js
  src/routes/api/auth/callback/+server.js
  src/routes/api/auth/me/+server.js
  src/routes/api/auth/proxy/+server.js
  src/routes/api/auth/signup/+server.js
  src/routes/event/+layout.js
  src/routes/event/check-in/[eventName]/[year]/+page.server.js
  src/routes/join/[activityId]/+layout.js
  src/routes/join/[activityId]/+page.server.js
  src/routes/login-redirect/+page.svelte
  src/routes/login/+server.js
  src/routes/logout/+server.js
  src/routes/my/+layout.js
  src/routes/my/+layout.server.js
  src/routes/news/submit/+page.js
  src/routes/news/submit/+page.server.js
  src/routes/partners/leads/+layout.js
  src/routes/partners/leads/[eventId]/+page.server.js
  src/routes/partners/my-network/+layout.js
  src/routes/partners/my-network/+page.server.js
  src/routes/signup/+page.server.js
  src/routes/signup/+page.svelte
  src/routes/speakers/+layout.js
  src/routes/speakers/+layout.server.js
Labels: enhancement, dependencies
