Repository ThatConference/that.us, pull requests merged in 2023-11, with the labels that each got.

#1492 Fix/favorites 401 & add security headers
  package.json
  src/lib/stores/favorites.js
  vercel.json
Labels: bug, enhancement

#1494 Feat/that join v2 copy
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/CardButton.svelte
  src/_components/activities/DiscordLinksModal.svelte
  src/_components/activities/List.svelte
  src/_dataSources/api.that.tech/sessions.js
  src/_elements/links/Standard.svelte
  src/routes/+layout.svelte
  src/routes/support/joining-an-activity/+page.svelte
  src/routes/support/staying-up-to-date/+page.svelte
Labels: enhancement

#1495 Promote Next/feature to production
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/CardButton.svelte
  src/_components/activities/DiscordLinksModal.svelte
  src/_components/activities/List.svelte
  src/_dataSources/api.that.tech/sessions.js
  src/_elements/links/Standard.svelte
  src/routes/+layout.svelte
  src/routes/support/joining-an-activity/+page.svelte
  src/routes/support/staying-up-to-date/+page.svelte
Labels: enhancement

#1496 Chore/sentry deny urls
  package.json
  src/_utils/config.public.js
  src/hooks.client.js
  src/hooks.server.js
Labels: chore, add-to-tc.com

#1497 promote Next/feature to production
  package.json
  src/_utils/config.public.js
  src/hooks.client.js
  src/hooks.server.js
Labels: chore

#1498 Specific success page for claim ticket type
  package-lock.json
  package.json
  src/_dataSources/api.that.tech/events/queries.js
  src/_utils/claimTicket/config.js
  src/_utils/claimTicket/machine.js
  src/routes/events/(online)/[event]/[date]/+page.svelte
  src/routes/events/(online)/_components/EventTicket.svelte
  src/routes/orders/_components/_ClaimCart.svelte
  src/routes/orders/success/claim-ticket/+page.svelte
  src/routes/orders/success/expo-hall-ticket/+page.svelte
  src/routes/support/sponsors/expo-hall/+page.svelte
Labels: enhancement

#1500 fix: viewport and formatting
  src/_components/activities/ActivityDetails.svelte
  src/app.html
Labels: bug

#1501 fix: issue where partner contact is null
  package.json
  src/app.html
  src/routes/my/network/sponsors/+page.svelte
Labels: bug, add-to-tc.com
