Repository ThatConference/that.us, pull requests merged in 2023-07, with the labels that each got.

#1409 update to nodejs 18
  .node-version
  package-lock.json
  package.json
Labels: chore

#1410 Promotes Next/feature to production
  .node-version
  package-lock.json
  package.json
  src/_components/footer/links.js
Labels: chore

#1412 Promote Next/feature to production
  package.json
  src/_components/banners/SuccessRounded.svelte
  src/routes/event/check-in/_components/_Ticket.svelte
  src/routes/partners/leads/[eventId]/+page.svelte
Labels: enhancement

#1413 refactor: digital signs for tv's
  package.json
  src/_dataSources/api.that.tech/partner/queries.js
  src/routes/signs/+page.js
  src/routes/signs/+page.svelte
  static/images/tv-background.png
Labels: enhancement

#1414 Promote next/feature to Production
  package.json
  src/_dataSources/api.that.tech/partner/queries.js
  src/routes/signs/+page.js
  src/routes/signs/+page.svelte
  static/images/sign-background.png
  static/images/tv-background.png
Labels: enhancement

#1415 Fix/my event tickets
  package.json
  src/_dataSources/api.that.tech/orders/queries.js
Labels: bug

#1416 Promote Next/feature to production
  package.json
  src/_dataSources/api.that.tech/orders/queries.js
Labels: bug

#1417 fix: cart not being cleard on success
  package.json
  src/routes/orders/success/+layout.svelte
Labels: bug, regression

#1419 refactor: partnerId
  package.json
  src/routes/partners/leads/+page.js
Labels: chore

#1420 refactor: partner id - feature merge
  package.json
  src/routes/partners/leads/+page.js
Labels: chore

#1421 refactor: upgrades sentry, and fixes navigating store on server
  .gitignore
  package-lock.json
  package.json
  sentry.properties
  src/_utils/config.public.js
  src/hooks.client.js
  src/hooks.server.js
  src/routes/+error.svelte
  src/routes/+layout.js
  src/routes/+layout.svelte
  vite.config.js
Labels: bug, chore

#1423 refactor: moved sentry reference to dependency
  package-lock.json
  package.json
Labels: sentry

#1424 Next/feature
  package.json
  src/_utils/gfetch.js
  src/routes/+layout.svelte
Labels: bug

#1425 chore: sentry source map config
  package.json
  vite.config.js
Labels: bug

#1426 feature -> master
  package.json
  vite.config.js
Labels: chore

#1427 Ensures instance of error is passed to sentry
  package.json
  src/_dataSources/api.that.tech/utilities/error.js
Labels: bug, sentry

#1429 refactor: fetch retry to only create one sentry event per retry
  package.json
  src/_utils/gfetch.js
Labels: sentry

#1430 Promote Next/feature to production
  package.json
  src/_utils/gfetch.js
Labels: sentry

#1433 Promote Next/feature to production
  package.json
  src/routes/activities/[activity]/+page.js
Labels: bug

#1434 fix: first render layout bug blocking page
  package-lock.json
  package.json
Labels: bug, critical

#1437 feat: adding routes listed on badges
  package.json
  src/routes/camp/+page.js
  src/routes/camp/+page.svelte
  src/routes/family/+page.js
  src/routes/family/+page.svelte
Labels: enhancement, chore

#1438 Feat/url filter family
  package.json
  src/_components/activities/List.svelte
  src/routes/events/(thatConferences)/wi/[year]/schedule/+page.js
  src/routes/events/(thatConferences)/wi/[year]/schedule/+page.svelte
  src/routes/events/_components/schedule/List.svelte
  src/routes/family/+page.js
Labels: enhancement

#1439 Promote Next/feature to production
  package.json
  src/_components/activities/List.svelte
  src/routes/events/(thatConferences)/wi/[year]/schedule/+page.js
  src/routes/events/(thatConferences)/wi/[year]/schedule/+page.svelte
  src/routes/events/_components/schedule/List.svelte
  src/routes/family/+page.js
Labels: enhancement

#1442 promote Next/feature to production
  .all-contributorsrc
  README.md
  package.json
  src/routes/my/favorites/+page.svelte
Labels: enhancement, ui/ux

#1443 Refactor/activities
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/List.svelte
  src/_dataSources/api.that.tech/sessions.js
  static/images/canceled-stamp.svg
Labels: enhancement

#1444 promote Next/feature to production
  package.json
  src/_components/activities/ActivityDetails.svelte
  src/_components/activities/Card.svelte
  src/_components/activities/List.svelte
  src/_dataSources/api.that.tech/sessions.js
  static/images/canceled-stamp.svg
Labels: enhancement

#1445 chore: Texas '24 days set to Mon-Thur
  package.json
  src/routes/events/(thatConferences)/tx/[year]/tickets/_components/data/pricing.js
Labels: chore

#1446 Promote Next/feature to production
  package.json
  src/routes/events/(thatConferences)/tx/[year]/tickets/_components/data/pricing.js
Labels: chore

#1448 fix: adding more details to the event on membership
  src/_dataSources/api.that.tech/products/queries.js
  src/routes/membership/+page.svelte
  src/routes/membership/_components/pricing/_Hero.svelte
  src/routes/membership/_machines/pricing.js
Labels: bug

#1449 Promote next/feature to production
  package.json
  src/routes/event/check-in/_components/_Ticket.svelte
Labels: bug
