Repository ThatConference/that.us, pull requests merged in 2023-03, with the labels that each got.

#1361 chore: update block date and rates
  src/_utils/config.public.js
  src/routes/support/travel/wi/+page.svelte
Labels: chore

#1364 Next/feature promoted to master
  src/routes/events/(thatConferences)/tx/[year]/tickets/_components/Families.svelte
  src/routes/events/(thatConferences)/wi/[year]/tickets/_components/Families.svelte
Labels: enhancement

#1365 Chore/hotel blocks
  src/_utils/config.public.js
  src/routes/support/travel/wi/+page.svelte
Labels: chore

#1366 Next/feature promote to production
  src/_utils/config.public.js
  src/routes/support/travel/wi/+page.svelte
Labels: chore

#1367 Next/feature promoted to production
  src/routes/speakers/_components/formSections/AcceptInvitation.svelte
  src/routes/speakers/_components/formSections/AtThatNextSteps.svelte
  src/routes/speakers/_components/formSections/CampsiteComps.svelte
  src/routes/speakers/_components/formSections/EmergencyContactInfo.svelte
  src/routes/speakers/_components/formSections/SelectTickets.svelte
  src/routes/speakers/_components/formSections/ThankYou.svelte
  src/routes/speakers/accept/+page.svelte
Labels: bug, enhancement

#1368 fix: broken room block warning being displaed
  src/routes/support/travel/wi/+page.svelte
Labels: bug

#1369 fix: missing jump buttons
  src/routes/events/(thatConferences)/wi/[year]/schedule/+page.svelte
Labels: bug, critical
