Repository ThatConference/that.us, pull requests merged in 2023-08, with the labels that each got.

#1450 fix: updating shortcut to wi 2024
  src/_utils/config.public.js
Labels: chore

#1452 Promote Next/feature to production
  package.json
  src/_components/activities/List.svelte
Labels: bug, regression

#1453 chore: trying out vercel analytics
  package-lock.json
  package.json
  src/routes/+layout.js
Labels: chore

#1454 fix: texas event details
  src/routes/events/(thatConferences)/tx/[year]/schedule/+page.svelte
  src/routes/events/(thatConferences)/tx/[year]/tickets/_components/data/pricing.js
Labels: enhancement
